// TIER 0 — the portable, static `Dashboard.md` renderer (ADR-0020 §1).
//
// `renderDashboardMarkdown(data)` folds a {@link DashboardData} snapshot into a
// single committable markdown document that opens in ANY markdown viewer. It is
// the "honest baseline" of the tiered dashboard: it carries a `last_refreshed`
// stamp and DRIFTS until regenerated — re-running `mage dashboard` refreshes it.
//
// Two invariants govern this renderer, both load-bearing:
//
//   1. DETERMINISM. Same `data` → identical bytes. Everything is sorted with a
//      stable comparator; nothing depends on map/object iteration order or the
//      wall clock beyond the explicit `meta.lastRefreshed` stamp. A re-run over
//      unchanged notes therefore produces NO git diff (mirrors `mage index`,
//      ADR-0006).
//
//   2. KNOWLEDGE HALF ONLY (ADR-0020 §6). Dashboard.md is committable, so it
//      renders ONLY the *tracked-notes* half: wings, notes, skills, and
//      health/provenance. It deliberately OMITS the grooming proposal queue and
//      any `.metrics/`-derived churny number (awaitingYou, graduateReady,
//      context-match rates, the recurrence ladder). Those live in the gitignored
//      HTML cockpit so this committable file never churns on every soak tick.
//
// The escaping/link-encoding matches `index-cmd.ts` EXACTLY (`escapeLinkText`,
// `encodePath`, `closetLine`, `lifecycleSuffix`) so a note row in Dashboard.md is
// byte-identical to its INDEX.md row.

import type {
  DashboardData,
  DashboardNote,
  DashboardSkill,
  DashboardWing,
} from "./types.js";

/** Mirror INDEX.md's generated banner (idempotent, do-not-hand-edit marker). */
const GEN_MARKER = "<!-- GENERATED by `mage dashboard` — do not edit by hand. -->";

/**
 * Render the portable static `Dashboard.md` (ADR-0020 tier 0). Deterministic:
 * identical `data` yields identical bytes. Renders the KNOWLEDGE half only —
 * wings, notes, skills, health — never the grooming queue or `.metrics` churn.
 */
export function renderDashboardMarkdown(data: DashboardData): string {
  const lines: string[] = [
    GEN_MARKER,
    "",
    `# ${escapeInline(data.meta.kbName)} — dashboard`,
    "",
    // Coarsen the refresh stamp to the DATE only (the `YYYY-MM-DD` prefix of the
    // ISO instant): same-day re-runs over unchanged notes produce NO git diff,
    // while still carrying an honest, drifting `last_refreshed` (ADR-0020 §6).
    // The precise wall-clock instant still lives in the gitignored HTML cockpit.
    `_Refreshed ${data.meta.lastRefreshed.slice(0, 10)} | ${data.meta.mageVersion}_`,
    "",
    kpiLine(data),
    "",
  ];

  pushWings(lines, data);
  pushSkills(lines, data.skills);
  pushHealth(lines, data);

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

// ─── KPI summary (knowledge-half numbers only) ───────────────────────────────

/**
 * The headline counts — notes / skills / wings only. We deliberately DO NOT
 * surface `awaitingYou`, `graduateReady`, or `contextMatchPct` here: those are
 * `.metrics`-derived and would churn this committable file on every soak tick
 * (ADR-0020 §6).
 */
function kpiLine(data: DashboardData): string {
  const { notes, skills, wings } = data.kpis;
  return `> ${notes} ${plural(notes, "note")} · ${skills} ${plural(skills, "skill")} · ${wings} ${plural(wings, "wing")}.`;
}

// ─── wings (per-wing counts, rooms, closet-line note entries) ────────────────

function pushWings(lines: string[], data: DashboardData): void {
  lines.push("## Wings", "");
  // Skip the sentinel empty-name wing: its notes are rendered in the dedicated
  // "Cross-cutting" section below, not as a nameless wing heading. (The collector
  // never emits an empty-name wing for real data; this is belt-and-suspenders.)
  const wings = data.wings.filter((w) => w.name !== "").sort(byName);
  if (wings.length === 0) {
    lines.push("_No wings yet._", "");
  }
  for (const wing of wings) {
    pushWing(lines, wing, data.notes);
  }

  // Cross-cutting notes (wing === "") get their own trailing section, mirroring
  // index-cmd's "Cross-cutting" group.
  const cross = data.notes.filter((n) => n.wing === "").sort(byRelPath);
  if (cross.length > 0) {
    lines.push("## Cross-cutting", "");
    for (const n of cross) lines.push(closetLine(n));
    lines.push("");
  }
}

function pushWing(lines: string[], wing: DashboardWing, notes: DashboardNote[]): void {
  const counts = `${wing.noteCount} ${plural(wing.noteCount, "note")} · ${wing.skillCount} ${plural(wing.skillCount, "skill")}`;
  lines.push(`## ${escapeInline(wing.name)} (${counts})`, "");

  if (wing.rooms && wing.rooms.length > 0) {
    lines.push(`> Rooms: ${[...wing.rooms].sort(byString).map(inlineCode).join(", ")}`, "");
  }

  // Notes tagged under THIS wing (multi-home: a note appears under EVERY wing it
  // is tagged in — ADR-0012 §5 — not only its primary). Mirrors index-cmd's
  // `e.wings.some(w => w.wing === wing)`, so the listed count matches noteCount.
  const inWing = notes.filter((n) => n.wings.some((w) => w.wing === wing.name)).sort(byRelPath);
  pushRooms(lines, inWing, wing.name);
}

/**
 * Append room-grouped closet lines for one wing's notes. The room is resolved
 * PER WING (a multi-homed note can sit in different rooms under different wings),
 * so we group by `n.wings.find(w => w.wing === wingName)?.room`, not the primary
 * `n.room`. Rooms sort with the no-room group first, mirroring index-cmd.
 */
function pushRooms(lines: string[], notes: DashboardNote[], wingName: string): void {
  const roomOf = (n: DashboardNote): string => n.wings.find((w) => w.wing === wingName)?.room ?? "";
  const rooms = [...new Set(notes.map(roomOf))].sort((a, b) => {
    if (a === "") return -1;
    if (b === "") return 1;
    return a < b ? -1 : a > b ? 1 : 0;
  });
  for (const room of rooms) {
    const group = notes.filter((n) => roomOf(n) === room).sort(byRelPath);
    if (room !== "") lines.push(`### ${escapeInline(room)}`, "");
    for (const n of group) lines.push(closetLine(n));
    lines.push("");
  }
  if (notes.length === 0) lines.push("_No notes._", "");
}

// ─── skills (name + wing + advisory status badge; NO churny context-match %) ──

function pushSkills(lines: string[], skills: DashboardSkill[]): void {
  lines.push("## Skills", "");
  if (skills.length === 0) {
    lines.push("_No skills yet._", "");
    return;
  }
  for (const s of [...skills].sort(byName)) {
    lines.push(skillLine(s));
  }
  lines.push("");
}

function skillLine(s: DashboardSkill): string {
  const wing = s.wing ? ` _(${escapeInline(s.wing)})_` : "";
  // Deliberately OMIT the numeric context-match %: it is `.metrics`/rollup-derived
  // and would churn this committable file on every soak tick (ADR-0020 §6). Only
  // the infrequently-changing status badge is kept; the precise % lives in the
  // gitignored HTML cockpit.
  const status = s.status && s.status !== "ok" ? ` _(${s.status})_` : "";
  return `- ${inlineCode(s.name)}${wing}${status}`;
}

// ─── health / provenance ─────────────────────────────────────────────────────

function pushHealth(lines: string[], data: DashboardData): void {
  const { notesDueForReview, danglingLinks, orphanNotes, lastCommit } = data.health;
  lines.push("## Health", "");
  lines.push(
    `- Due for review: ${notesDueForReview}`,
    `- Dangling links: ${danglingLinks}`,
    `- Orphan notes: ${orphanNotes}`,
  );
  if (lastCommit) {
    lines.push(`- Last commit: \`${shortHash(lastCommit.hash)}\` (${lastCommit.when})`);
  } else {
    lines.push("- Last commit: _(not a git repo)_");
  }
  lines.push("");
}

/** Short the commit hash to its first 8 chars (purely cosmetic, deterministic). */
function shortHash(hash: string): string {
  return hash.slice(0, 8);
}

// ─── closet line + escaping (MATCHES index-cmd.ts byte-for-byte) ─────────────

/**
 * A single note's closet-line row — IDENTICAL in shape to `index-cmd.closetLine`:
 * `` - `type` [title](relPath) — keyword, keyword _(status · reviewed …)_ ``.
 */
function closetLine(n: DashboardNote): string {
  const kw = n.keywords.length ? ` — ${n.keywords.join(", ")}` : "";
  return `- \`${n.type}\` [${escapeLinkText(n.title)}](${encodePath(n.relPath)})${kw}${lifecycleSuffix(n)}`;
}

/** The trailing `_(status · reviewed YYYY-MM-DD)_` suffix (mirrors index-cmd). */
function lifecycleSuffix(n: DashboardNote): string {
  const bits: string[] = [];
  if (n.status && n.status !== "active") bits.push(n.status);
  if (n.lastReviewed) bits.push(`reviewed ${n.lastReviewed}`);
  return bits.length ? ` _(${bits.join(" · ")})_` : "";
}

/** Escape `]` so it can't close the markdown link text early (index-cmd parity). */
function escapeLinkText(s: string): string {
  return s.replace(/\]/g, "\\]");
}

/**
 * Make a relative path safe as a markdown link destination — percent-encode each
 * segment (preserving `/`) AND escape parens, identical to `index-cmd.encodePath`.
 */
function encodePath(p: string): string {
  return p
    .split("/")
    .map((seg) => encodeURIComponent(seg).replace(/\(/g, "%28").replace(/\)/g, "%29"))
    .join("/");
}

/** Escape characters that would break an inline (heading/quote) markdown context. */
function escapeInline(s: string): string {
  return s.replace(/([\\`*_[\]<>])/g, "\\$1");
}

/** Wrap a value in inline code, escaping any backticks in it. */
function inlineCode(s: string): string {
  return `\`${s.replace(/`/g, "")}\``;
}

// ─── deterministic comparators ───────────────────────────────────────────────

function byString(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function byName(a: { name: string }, b: { name: string }): number {
  return byString(a.name, b.name);
}

function byRelPath(a: { relPath: string }, b: { relPath: string }): number {
  return byString(a.relPath, b.relPath);
}

function plural(n: number, word: string): string {
  return n === 1 ? word : `${word}s`;
}
