import { describe, expect, it } from "vitest";
import { renderDashboardMarkdown } from "./markdown.js";
import type { DashboardData } from "./types.js";

// ─── fixture ─────────────────────────────────────────────────────────────────

/**
 * A small, fully-typed fixture KB: 2 wings (`alpha` with a `core` room, `beta`),
 * a cross-cutting note, 2 skills (one healthy, one demote-suggested), and a
 * populated health block. Deliberately includes `.metrics`-derived fields
 * (proposals, awaitingYou, graduateReady, contextMatchPct, ladder) so the test
 * can assert they are NOT leaked into the committable markdown (ADR-0020 §6).
 */
function fixture(): DashboardData {
  return {
    meta: {
      kbName: "demo",
      kind: "in-repo",
      root: "/abs/demo/mage",
      mageVersion: "9.9.9",
      lastRefreshed: "2026-06-09T12:00:00.000Z",
    },
    kpis: {
      notes: 4,
      skills: 2,
      wings: 2,
      contextMatchPct: 73,
      awaitingYou: 3,
      graduateReady: 1,
    },
    proposals: [
      { kind: "graduate", target: "notes/alpha/a1.md", why: "recurred 5x" },
      { kind: "note", target: "sig:xyz", why: "seen across sessions" },
    ],
    wings: [
      // intentionally UNSORTED to prove the renderer sorts.
      { name: "beta", noteCount: 1, skillCount: 0 },
      { name: "alpha", noteCount: 2, skillCount: 1, rooms: ["core"] },
    ],
    notes: [
      // intentionally UNSORTED to prove deterministic ordering by relPath.
      {
        title: "Beta one",
        type: "note",
        wing: "beta",
        room: "",
        wings: [{ wing: "beta", room: "" }],
        keywords: ["b", "beta"],
        relPath: "notes/beta/b1.md",
        obsidianFile: "notes/beta/b1.md",
      },
      {
        title: "Alpha two [draft]",
        type: "decision",
        wing: "alpha",
        room: "core",
        wings: [{ wing: "alpha", room: "core" }],
        keywords: ["a2"],
        status: "stale-suspect",
        lastReviewed: "2026-01-01",
        relPath: "notes/alpha/a2.md",
        obsidianFile: "notes/alpha/a2.md",
      },
      {
        title: "Alpha one",
        type: "note",
        wing: "alpha",
        room: "core",
        wings: [{ wing: "alpha", room: "core" }],
        keywords: ["a1"],
        relPath: "notes/alpha/a1.md",
        obsidianFile: "notes/alpha/a1.md",
      },
      {
        title: "Cross note",
        type: "note",
        wing: "",
        room: "",
        wings: [],
        keywords: [],
        relPath: "notes/cross.md",
        obsidianFile: "notes/cross.md",
      },
    ],
    skills: [
      // unsorted; renderer must sort by name.
      { name: "beta:tools", wing: "beta", contextMatchPct: 40, status: "demote-suggested" },
      { name: "alpha:core", wing: "alpha", contextMatchPct: 90, status: "ok" },
    ],
    graph: { nodes: [], edges: [] },
    activity: [],
    ladder: { scratch: 12, notes: 4, skills: 2, climbing: [{ sessions: 3, count: 1 }] },
    health: {
      notesDueForReview: 2,
      danglingLinks: 1,
      orphanNotes: 0,
      lastCommit: { hash: "abcdef0123456789", when: "2026-06-08T10:00:00.000Z" },
    },
  };
}

// ─── tests ───────────────────────────────────────────────────────────────────

describe("renderDashboardMarkdown", () => {
  it("emits the generated banner, title, refresh stamp, and KPI line", () => {
    const md = renderDashboardMarkdown(fixture());
    expect(md.startsWith("<!-- GENERATED by `mage dashboard` — do not edit by hand. -->\n")).toBe(
      true,
    );
    expect(md).toContain("# demo — dashboard");
    // The refresh stamp is coarsened to the DATE only (no wall-clock instant) so
    // same-day re-runs produce no churn (ADR-0020 §6).
    expect(md).toContain("_Refreshed 2026-06-09 | 9.9.9_");
    expect(md).not.toContain("2026-06-09T12:00:00.000Z"); // no full instant in the committable file.
    expect(md).toContain("> 4 notes · 2 skills · 2 wings.");
  });

  it("renders wings with note/skill counts, rooms, and closet-line entries", () => {
    const md = renderDashboardMarkdown(fixture());
    expect(md).toContain("## alpha (2 notes · 1 skill)");
    expect(md).toContain("## beta (1 note · 0 skills)");
    expect(md).toContain("> Rooms: `core`");
    expect(md).toContain("### core");
    // closet line matches index-cmd format exactly: `type` [title](relPath) — kw.
    expect(md).toContain("- `note` [Alpha one](notes/alpha/a1.md) — a1");
  });

  it("escapes link text and percent-encodes paths like index-cmd; renders lifecycle", () => {
    const md = renderDashboardMarkdown(fixture());
    // index-cmd's escapeLinkText escapes only the CLOSING `]` (the one that would
    // end the link text early), leaving `[` raw; status + reviewed render in the
    // suffix. This must be byte-identical to the INDEX.md row.
    expect(md).toContain(
      "- `decision` [Alpha two [draft\\]](notes/alpha/a2.md) — a2 _(stale-suspect · reviewed 2026-01-01)_",
    );
  });

  it("groups cross-cutting (wing === '') notes in their own section", () => {
    const md = renderDashboardMarkdown(fixture());
    expect(md).toContain("## Cross-cutting");
    expect(md).toContain("- `note` [Cross note](notes/cross.md)");
  });

  it("lists a multi-homed note under EVERY wing it is tagged in (ADR-0012 §5)", () => {
    // A note homed in BOTH `alpha` (room core) and `beta` (no room) must appear
    // under both wing sections, and each wing's listed-note count must equal its
    // header noteCount.
    const data: DashboardData = {
      ...fixture(),
      wings: [
        { name: "alpha", noteCount: 1, skillCount: 0, rooms: ["core"] },
        { name: "beta", noteCount: 1, skillCount: 0 },
      ],
      notes: [
        {
          title: "Shared note",
          type: "note",
          wing: "alpha",
          room: "core",
          wings: [
            { wing: "alpha", room: "core" },
            { wing: "beta", room: "" },
          ],
          keywords: ["shared"],
          relPath: "notes/shared.md",
          obsidianFile: "notes/shared.md",
        },
      ],
      skills: [],
    };
    const md = renderDashboardMarkdown(data);

    // Appears under both wing headers.
    const alphaHeader = md.indexOf("## alpha (1 note · 0 skills)");
    const betaHeader = md.indexOf("## beta (1 note · 0 skills)");
    expect(alphaHeader).toBeGreaterThan(-1);
    expect(betaHeader).toBeGreaterThan(-1);

    // The note's closet line appears TWICE (once under each wing).
    const closet = "- `note` [Shared note](notes/shared.md) — shared";
    const occurrences = md.split(closet).length - 1;
    expect(occurrences).toBe(2);

    // Under alpha it sits in the `core` room; under beta it is roomless.
    const alphaSection = md.slice(alphaHeader, betaHeader);
    expect(alphaSection).toContain("### core");
    expect(alphaSection).toContain(closet);

    // Per-wing listed-note count equals header noteCount (1 each).
    const betaSection = md.slice(betaHeader);
    const countIn = (section: string): number => section.split(closet).length - 1;
    expect(countIn(alphaSection)).toBe(1);
    expect(countIn(betaSection)).toBe(1);
  });

  it("never renders a nameless wing heading for a sentinel empty-name wing", () => {
    const withEmptyWing: DashboardData = {
      ...fixture(),
      wings: [...fixture().wings, { name: "", noteCount: 1, skillCount: 0 }],
    };
    const md = renderDashboardMarkdown(withEmptyWing);
    // no `## ` heading followed immediately by `(` (the nameless-wing shape).
    expect(md).not.toMatch(/^## \(/m);
  });

  it("renders skills sorted, with wing + status badge but NO churny context-match %", () => {
    const md = renderDashboardMarkdown(fixture());
    const alphaIdx = md.indexOf("`alpha:core`");
    const betaIdx = md.indexOf("`beta:tools`");
    expect(alphaIdx).toBeGreaterThan(-1);
    expect(betaIdx).toBeGreaterThan(alphaIdx); // sorted: alpha before beta.
    // The numeric context-match % is OMITTED (it's `.metrics`-derived churn,
    // ADR-0020 §6); only wing + the infrequently-changing status badge render.
    expect(md).toContain("- `alpha:core` _(alpha)_");
    expect(md).toContain("- `beta:tools` _(beta)_ _(demote-suggested)_");
    expect(md).not.toContain("context-match");
    expect(md).not.toContain("90%");
    expect(md).not.toContain("40%");
  });

  it("renders the health/provenance section with the short commit hash", () => {
    const md = renderDashboardMarkdown(fixture());
    expect(md).toContain("## Health");
    expect(md).toContain("- Due for review: 2");
    expect(md).toContain("- Dangling links: 1");
    expect(md).toContain("- Orphan notes: 0");
    expect(md).toContain("- Last commit: `abcdef01` (2026-06-08T10:00:00.000Z)");
  });

  it("OMITS the grooming queue and .metrics-derived churn (ADR-0020 §6)", () => {
    const md = renderDashboardMarkdown(fixture());
    // no proposal targets / queue language.
    expect(md).not.toContain("Awaiting");
    expect(md).not.toContain("sig:xyz");
    expect(md).not.toContain("recurred 5x");
    // no whole-KB context-match %, no ladder scratch count.
    expect(md).not.toContain("73%");
    expect(md).not.toContain("scratch");
    expect(md).not.toContain("graduate");
  });

  it("is deterministic — same data yields identical bytes", () => {
    const a = renderDashboardMarkdown(fixture());
    const b = renderDashboardMarkdown(fixture());
    expect(a).toBe(b);
    // ends with exactly one trailing newline.
    expect(a.endsWith("\n")).toBe(true);
    expect(a.endsWith("\n\n")).toBe(false);
  });

  it("degrades to empty-state markdown for an empty KB without throwing", () => {
    const empty: DashboardData = {
      ...fixture(),
      kpis: { notes: 0, skills: 0, wings: 0, contextMatchPct: 0, awaitingYou: 0, graduateReady: 0 },
      proposals: [],
      wings: [],
      notes: [],
      skills: [],
      health: { notesDueForReview: 0, danglingLinks: 0, orphanNotes: 0, lastCommit: null },
    };
    const md = renderDashboardMarkdown(empty);
    expect(md).toContain("> 0 notes · 0 skills · 0 wings.");
    expect(md).toContain("_No wings yet._");
    expect(md).toContain("_No skills yet._");
    expect(md).toContain("- Last commit: _(not a git repo)_");
  });
});
