import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  AUTO_MEMORY_MAX_BYTES,
  AUTO_MEMORY_MAX_LINES,
} from "../adapters/claude-code/constants.js";
import { logger } from "../logger.js";
import { BREACH_RATIO } from "../metrics/footprint.js";
import { updateGraphColorGroups } from "../obsidian.js";
import {
  type HubProject,
  INDEX_FILE,
  MEMORY_FILE,
  readGenreOverrides,
  readHubMetadata,
  requireDocsRoot,
} from "../paths.js";
import { type ScannedNote, scanNotes } from "../scan.js";
import { readSensitivity } from "../grooming/config.js";
import { readTally } from "../grooming/tally.js";
import type { PromoteTally } from "../grooming/types.js";
import { thresholdsFor } from "../grooming/thresholds.js";
import { genreOf } from "../scanner/genre-map.js";

const GEN_MARKER = "<!-- GENERATED by `mage index` — do not edit by hand. -->";
/** Below these bounds the index stays a single flat file; past them it goes hierarchical. */
const FLAT_MAX_WINGS = 4;
const FLAT_MAX_NOTES = 20;

export interface IndexOptions {
  /** Where to look for the knowledge base (default cwd; walks up for in-repo). */
  dir?: string;
  /** Suppress the human success/detail logging (for callers emitting JSON on stdout). */
  quiet?: boolean;
}

export interface IndexResult {
  root: string;
  noteCount: number;
  wings: string[];
  hierarchical: boolean;
  written: string[];
  memoryTier: 0 | 1 | 2;
}

/**
 * Generate the hierarchical INDEX (the always-loaded "closet"). Deterministic
 * and idempotent: same notes → identical output, re-run → no diff (ADR-0006).
 */
export async function index(opts: IndexOptions = {}): Promise<IndexResult> {
  const resolved = await requireDocsRoot(opts.dir);
  const root = resolved.root;

  const entries = await scanNotes(root);
  const overrides = await readGenreOverrides(resolved, !opts.quiet);

  const memoryEntries = entries.filter(
    (e) => genreOf(e.type, overrides) === "memory",
  );
  const acceptedDecisionsCount = entries.filter(
    (e) =>
      genreOf(e.type, overrides) === "decision" &&
      (e.status === "accepted" || e.status === "active"),
  ).length;

  // Wings are the UNION of tag-wings (multi-home, ADR-0012 §5), split in two:
  //  - `wings` (memory genre) drives the RECALL surface — the root index's wing map,
  //    its note lines, and the header counts (ADR-0041 §4).
  //  - `allWings` (every genre) drives the per-wing index FILE set and the Obsidian
  //    graph groups. `mage skills` generates a skill per all-notes wing pointing at
  //    `_index.<wing>.md`; deriving the file set from memory wings alone deleted that
  //    target for a document-only wing and left the skill pointing at nothing.
  const wings = [
    ...new Set(memoryEntries.flatMap((e) => e.wings.map((w) => w.wing))),
  ].sort();
  const allWings = [
    ...new Set(entries.flatMap((e) => e.wings.map((w) => w.wing))),
  ].sort();
  const hierarchical =
    wings.length > FLAT_MAX_WINGS || memoryEntries.length > FLAT_MAX_NOTES;

  // Registry decorates the index (code-repo pointers, in-repo-member pointers) but
  // never drives grouping — notes are found/grouped by tag/wing alone (ADR-0011 §3).
  const hubMeta = resolved.kind === "hub" ? await readHubMetadata(root) : null;
  const registry = buildRegistryView(hubMeta?.projects ?? []);

  // Remove stale generated per-wing index files (idempotency across mode flips).
  await cleanGeneratedWingIndexes(root, hierarchical ? allWings : []);

  const written: string[] = [];
  if (hierarchical) {
    await writeFile(
      join(root, INDEX_FILE),
      renderRootHierarchical(
        memoryEntries,
        wings,
        registry,
        undefined,
        acceptedDecisionsCount,
      ),
    );
    written.push(INDEX_FILE);
    // One file per ALL-notes wing; the LINES inside stay memory-genre filtered, so a
    // document-only wing renders its header (and its pointer back to the index, which
    // carries the governance line) with zero note lines.
    for (const wing of allWings) {
      const file = `_index.${wing}.md`;
      await writeFile(
        join(root, file),
        renderWing(wing, wingEntries(memoryEntries, wing), registry),
      );
      written.push(file);
    }
  } else {
    await writeFile(
      join(root, INDEX_FILE),
      renderFlat(
        memoryEntries,
        wings,
        registry,
        0,
        undefined,
        acceptedDecisionsCount,
      ),
    );
    written.push(INDEX_FILE);
  }

  // The Claude Code adapter twin (ADR-0032/0033/0041): always emit MEMORY.md at the
  // docs-root top so CC's `autoMemoryDirectory` auto-loads it. For a single-wing
  // (or flat) KB it folds the per-note list inline as a bounded roster; for a
  // multi-wing hierarchical KB it stays the bounded wings-map twin.
  const sensitivity = await readSensitivity(resolved);
  const { graduateSessions } = thresholdsFor(sensitivity);
  const tally = await readTally(root);
  // The host's own budget, derived HERE and passed in (ADR-0041 Amendment §2): K falls
  // out of these two numbers, so a second harness supplies its own and gets its own K.
  const budget: RosterBudget = {
    byteThreshold: Math.floor(BREACH_RATIO * AUTO_MEMORY_MAX_BYTES),
    lineThreshold: Math.floor(BREACH_RATIO * AUTO_MEMORY_MAX_LINES),
  };

  const { content: memoryContent, tier: memoryTier } = renderMemory(
    memoryEntries,
    wings,
    hierarchical,
    registry,
    !opts.quiet,
    acceptedDecisionsCount,
    tally,
    graduateSessions,
    budget,
  );
  await writeFile(join(root, MEMORY_FILE), memoryContent);
  written.push(MEMORY_FILE);

  // Keep the Obsidian graph colored by wing (no-op without .obsidian/graph.json).
  // The graph shows every note, so it colors every wing — not just the memory ones.
  await updateGraphColorGroups(root, allWings);

  if (!opts.quiet) {
    logger.success(
      `Indexed ${memoryEntries.length} note(s) across ${wings.length} wing(s) → ${written.length} file(s) (${
        hierarchical ? "hierarchical" : "flat"
      }).`,
    );
    for (const w of written) logger.detail(w);
  }
  return {
    root,
    noteCount: memoryEntries.length,
    wings,
    hierarchical,
    written,
    memoryTier,
  };
}

// ─── registry decoration (ADR-0011 §3, ADR-0012 §2) ──────────────────────────

interface RegistryView {
  /** wing name → code-repo reference (url ?? path), for heading decoration. */
  decorationByWing: Map<string, string>;
  /** in-repo members: notes live in their own repo; shown as a pointer, never empty. */
  inRepoMembers: Array<{ name: string; codeRepoPath: string }>;
}

function buildRegistryView(projects: HubProject[]): RegistryView {
  const decorationByWing = new Map<string, string>();
  for (const p of projects)
    decorationByWing.set(p.name, p.code_repo_url || p.code_repo_path);
  const inRepoMembers = projects
    .filter((p) => p.storage === "repo-owned")
    .map((p) => ({ name: p.name, codeRepoPath: p.code_repo_path }))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return { decorationByWing, inRepoMembers };
}

/** Notes tagged under `wing` (multi-home: a note appears under every tag-wing). */
function wingEntries(entries: ScannedNote[], wing: string): ScannedNote[] {
  return entries.filter((e) => e.wings.some((w) => w.wing === wing));
}

/** The room a note occupies *within a given wing* (not necessarily its primary room). */
function roomForWing(e: ScannedNote, wing: string): string {
  return e.wings.find((w) => w.wing === wing)?.room ?? "";
}

function wingDecoration(reg: RegistryView, wing: string): string {
  const ref = reg.decorationByWing.get(wing);
  return ref ? ` — code repo: \`${ref}\`` : "";
}

/** A satellite section so an in-repo member is visible even with zero hub-owned notes. */
function pushLinkedRepos(lines: string[], reg: RegistryView): void {
  if (reg.inRepoMembers.length === 0) return;
  lines.push("## Linked repositories", "");
  for (const m of reg.inRepoMembers) {
    lines.push(
      `- **${m.name}** — notes live in \`${m.codeRepoPath}/mage\` → open its INDEX (in-repo member)`,
    );
  }
  lines.push("");
}

// ─── rendering ───────────────────────────────────────────────────────────────

function renderFlat(
  entries: ScannedNote[],
  wings: string[],
  reg: RegistryView,
  tier: 0 | 1 = 0,
  blockquote?: string,
  acceptedDecisionsCount = 0,
): string {
  const lines: string[] = [
    GEN_MARKER,
    "",
    "# Index",
    "",
    gist(entries.length, wings.length),
  ];
  if (blockquote) lines.push("", `> ${blockquote}`);
  lines.push("");
  for (const wing of wings) {
    lines.push(`## ${wing}${wingDecoration(reg, wing)}`, "");
    pushRooms(lines, wingEntries(entries, wing), wing, 3, tier); // root index: rooms sit under `## wing`
  }
  const cross = entries.filter((e) => e.wings.length === 0);
  if (cross.length > 0) {
    lines.push("## Cross-cutting", "");
    for (const e of cross) lines.push(closetLine(e, tier));
    lines.push("");
  }
  pushLinkedRepos(lines, reg);
  if (entries.length === 0 && reg.inRepoMembers.length === 0) {
    lines.push(
      "_No notes yet. Add notes under `notes/` and re-run `mage index`._",
      "",
    );
  }
  if (acceptedDecisionsCount > 0) {
    lines.push(governanceLine(acceptedDecisionsCount), "");
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

/**
 * The ONE standing governance line (ADR-0041 Amendment §1). Shared by every recall
 * surface — the root index, the wings map, and the bounded MEMORY.md roster — so the
 * three cannot drift into three different sentences.
 */
function governanceLine(acceptedDecisionsCount: number): string {
  const noun =
    acceptedDecisionsCount === 1 ? "decision governs" : "decisions govern";
  return `> ${acceptedDecisionsCount} accepted ${noun} this repo — read \`decisions/\` before architectural or scope changes.`;
}

function renderRootHierarchical(
  entries: ScannedNote[],
  wings: string[],
  reg: RegistryView,
  blockquote?: string,
  acceptedDecisionsCount = 0,
): string {
  const lines: string[] = [
    GEN_MARKER,
    "",
    "# Index",
    "",
    gist(entries.length, wings.length),
  ];
  if (blockquote) lines.push("", `> ${blockquote}`);
  lines.push("", "## Wings", "");
  for (const wing of wings) {
    const we = wingEntries(entries, wing);
    const types = [...new Set(we.map((e) => e.type))].sort().join(", ");
    lines.push(
      `- **${wing}** (${we.length} ${plural(we.length, "note")} · ${types})${wingDecoration(reg, wing)} → [_index.${wing}.md](${encodePath(`_index.${wing}.md`)})`,
    );
  }
  lines.push("");
  const cross = entries.filter((e) => e.wings.length === 0);
  if (cross.length > 0) {
    lines.push("## Cross-cutting", "");
    for (const e of cross) lines.push(closetLine(e));
    lines.push("");
  }
  pushLinkedRepos(lines, reg);
  if (acceptedDecisionsCount > 0) {
    lines.push(governanceLine(acceptedDecisionsCount), "");
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

/**
 * Note on ranking: ranking consults local metrics when present (ADR-0041 Amendment §3);
 * machines without metrics render the recency order — a deliberate, documented exception
 * to the byte-identical re-run contract stated in `index()`'s header comment above.
 */
function rankMemoryNotes(
  entries: ScannedNote[],
  tally: PromoteTally | undefined,
  graduateSessions: number,
): ScannedNote[] {
  const noteChapters = (relPath: string): number =>
    tally?.notes?.[relPath]?.chapters ?? 0;

  const noteRecency = (e: ScannedNote): string | undefined =>
    e.lastReviewed ?? e.updated ?? e.created;

  return [...entries].sort((a, b) => {
    // 1. Usage-proven flag, proven first
    const aProven = noteChapters(a.relPath) >= graduateSessions;
    const bProven = noteChapters(b.relPath) >= graduateSessions;
    if (aProven !== bProven) return aProven ? -1 : 1;

    // 2. Recency, newest first
    const aDate = noteRecency(a);
    const bDate = noteRecency(b);
    if (aDate !== bDate) {
      if (aDate !== undefined && bDate !== undefined) {
        return aDate > bDate ? -1 : 1;
      }
      if (aDate !== undefined) return -1;
      if (bDate !== undefined) return 1;
    }

    // 3. relPath ascending
    return a.relPath < b.relPath ? -1 : a.relPath > b.relPath ? 1 : 0;
  });
}

/**
 * The host budget the roster is held against — the caller's own constants scaled by the
 * `BREACH_RATIO` ladder (ADR-0041 Amendment §2/§4). Passed in, never re-derived here, so
 * a second harness brings its own numbers and gets its own K.
 */
export interface RosterBudget {
  byteThreshold: number;
  lineThreshold: number;
}

/** A rendered line's cost in bytes, including the `\n` that follows it. */
function lineCost(line: string): number {
  return Buffer.byteLength(line, "utf8") + 1;
}

/** The overflow line (ADR-0041 Amendment §1): the total, what is shown, and the pointer. */
function overflowLine(total: number, shown: number): string {
  return `> ${total} memory ${plural(total, "note")} total (${shown} shown). Read INDEX.md before non-trivial work.`;
}

interface RosterFill {
  content: string;
  /** K — entries actually rendered. */
  shown: number;
  /** An entry was rendered without its keyword tail to fit. */
  degraded: boolean;
  /** An entry did not fit even stripped bare, and was skipped. */
  omitted: boolean;
  /** The fixed structure alone breaches the budget — the caller must fall back. */
  structureBreaches: boolean;
}

/**
 * Fill the roster in rank order against a running line/byte total — O(N), one pass, never
 * a re-render per candidate K.
 *
 * Each entry is offered a LADDER rather than an all-or-nothing prefix cut: its full line
 * first, then the keyword-less line (tier 1's keyword shed, repurposed per-entry), and
 * only then is it skipped so lower-ranked entries keep filling. A prefix-only cut let ONE
 * bloated note at rank 1 zero the whole roster — 51 notes rendering `(0 shown)` — which is
 * the opposite of what a recall surface is for.
 *
 * The accounting reserves the fixed structure BEFORE any entry is admitted, and reserves
 * it conservatively: the overflow line at its maximal width (`total` shown, the widest the
 * count can print) and the blank separator unconditionally. Over-reserving only ever makes
 * the fill stricter, so the finished document cannot exceed either threshold.
 */
function fillRoster(
  ranked: ScannedNote[],
  acceptedDecisionsCount: number,
  budget: RosterBudget,
): RosterFill {
  const total = ranked.length;
  const header = [GEN_MARKER, "", "# Index", ""];
  const governance =
    acceptedDecisionsCount > 0
      ? [governanceLine(acceptedDecisionsCount), ""]
      : [];

  // Structure alone = the zero-entry document (no separator). Breaching THAT is the
  // pathological case tier 2 exists for; it is reachable for any host whose budget is
  // too small to carry the governance line and the pointer.
  const structure = [...header, ...governance, overflowLine(total, 0)];
  if (
    structure.length > budget.lineThreshold ||
    structure.reduce((n, l) => n + lineCost(l), 0) > budget.byteThreshold
  ) {
    return {
      content: "",
      shown: 0,
      degraded: false,
      omitted: false,
      structureBreaches: true,
    };
  }

  const reserved = [...header, ...governance, "", overflowLine(total, total)];
  let usedLines = reserved.length;
  let usedBytes = reserved.reduce((n, l) => n + lineCost(l), 0);

  const rendered: string[] = [];
  let degraded = false;
  let omitted = false;

  for (const e of ranked) {
    // Every entry costs exactly one line, so once the line budget is spent no
    // lower-ranked entry can fit either — stop rather than scan the tail.
    if (usedLines + 1 > budget.lineThreshold) {
      omitted = true;
      break;
    }
    const full = closetLine(e, 0);
    const bare = closetLine(e, 1);
    let line: string | undefined;
    if (usedBytes + lineCost(full) <= budget.byteThreshold) {
      line = full;
    } else if (usedBytes + lineCost(bare) <= budget.byteThreshold) {
      line = bare;
      degraded = true;
    }
    if (line === undefined) {
      omitted = true; // oversized even bare — skip it, keep filling.
      continue;
    }
    rendered.push(line);
    usedLines++;
    usedBytes += lineCost(line);
  }

  const lines = [...header, ...governance, ...rendered];
  if (rendered.length > 0) lines.push("");
  lines.push(overflowLine(total, rendered.length), "");
  return {
    content: `${lines.join("\n").replace(/\n+$/, "")}\n`,
    shown: rendered.length,
    degraded,
    omitted,
    structureBreaches: false,
  };
}

/**
 * MEMORY.md content — the Claude Code adapter twin of INDEX.md (ADR-0032/0033/0041).
 * A single-wing (or flat) KB folds the top-K memory entries inline as a roster bounded by
 * construction (lines AND bytes, whichever binds first).
 * Multi-wing hierarchical KBs stay the bounded wings-map twin.
 *
 * Tiers (Amendment §4 — the existing ladder, not a new parallel budget):
 *  - 0: every entry rendered in full.
 *  - 1: at least one entry lost its keyword tail or was skipped; the overflow line
 *       carries the count that the old omission blockquote used to.
 *  - 2: the fixed structure alone breaches — fall back to the category map.
 */
export function renderMemory(
  entries: ScannedNote[],
  wings: string[],
  hierarchical: boolean,
  reg: RegistryView,
  logWarn: boolean,
  acceptedDecisionsCount: number,
  tally: PromoteTally | undefined,
  graduateSessions: number,
  budget: RosterBudget,
): { content: string; tier: 0 | 1 | 2 } {
  const foldInline = !hierarchical || wings.length <= 1;

  if (!foldInline) {
    return {
      content: renderRootHierarchical(
        entries,
        wings,
        reg,
        undefined,
        acceptedDecisionsCount,
      ),
      tier: 0,
    };
  }

  const ranked = rankMemoryNotes(entries, tally, graduateSessions);
  const roster = fillRoster(ranked, acceptedDecisionsCount, budget);

  if (!roster.structureBreaches) {
    if (!roster.degraded && !roster.omitted) {
      return { content: roster.content, tier: 0 };
    }
    if (logWarn) {
      const cut =
        roster.shown < ranked.length
          ? `bounded to ${roster.shown} of ${ranked.length} entries — the rest are in INDEX.md`
          : "";
      const shed = roster.degraded
        ? "keyword tails shed where an entry was too wide for the budget"
        : "";
      logger.warn(
        `MEMORY.md roster: ${[cut, shed].filter(Boolean).join("; ")}.`,
      );
    }
    return { content: roster.content, tier: 1 };
  }

  const msg =
    "Fallen back to category map — recall structure exceeded budget.";
  const content = renderRootHierarchical(
    entries,
    wings,
    reg,
    msg,
    acceptedDecisionsCount,
  );
  if (logWarn) logger.warn(msg);
  return { content, tier: 2 };
}

function renderWing(
  wing: string,
  entries: ScannedNote[],
  reg: RegistryView,
): string {
  const lines: string[] = [
    GEN_MARKER,
    "",
    `# ${wing}${wingDecoration(reg, wing)}`,
    "",
    `> ${entries.length} ${plural(entries.length, "note")}. Part of the [index](INDEX.md).`,
    "",
  ];
  pushRooms(lines, entries, wing, 2, 0); // per-wing index: the wing is the `#` title
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

/**
 * Append room-grouped closet lines for one wing (rooms sorted; the no-room group
 * first, unlabeled). A note's room is resolved *per wing* so a multi-homed note
 * sits under the right room in each wing it's listed in.
 *
 * `depth` is the room heading level, and it differs by document: the ROOT index nests
 * rooms under an `## wing` heading (so rooms are `###`), while a per-wing index has the
 * wing as its `#` title (so rooms are `##`). Hardcoding `###` skipped a level in the
 * per-wing file — an MD001 violation in a GENERATED artifact, which can only be fixed
 * here, never by editing the output.
 */
function pushRooms(
  lines: string[],
  entries: ScannedNote[],
  wing: string,
  depth: 2 | 3,
  tier: 0 | 1 = 0,
): void {
  const roomOf = (e: ScannedNote) => roomForWing(e, wing);
  const rooms = [...new Set(entries.map(roomOf))].sort((a, b) => {
    if (a === "") return -1;
    if (b === "") return 1;
    return a < b ? -1 : a > b ? 1 : 0;
  });
  for (const room of rooms) {
    const group = entries.filter((e) => roomOf(e) === room);
    if (room !== "") lines.push(`${"#".repeat(depth)} ${room}`, "");
    for (const e of group) lines.push(closetLine(e, tier));
    lines.push("");
  }
}

export const SCAFFOLDING_WORDS = [
  "considered",
  "options",
  "consequences",
  "relations",
  "context",
  "decision",
];

function dedupeKeywords(e: ScannedNote): string[] {
  if (!e.keywords.length) return [];
  const normalize = (s: string) =>
    s
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(Boolean);
  const allParts = new Set([
    ...normalize(e.title),
    ...normalize(e.relPath),
    ...normalize(e.type),
  ]);
  const scaffold = new Set(SCAFFOLDING_WORDS);

  return e.keywords.filter((k) => {
    if (scaffold.has(k.trim().toLowerCase())) return false;
    const parts = normalize(k);
    if (parts.length === 0) return true;
    return !parts.every((p) => allParts.has(p));
  });
}

function closetLine(e: ScannedNote, tier: 0 | 1 = 0): string {
  const kept = dedupeKeywords(e);
  const kw = tier < 1 && kept.length ? ` — ${kept.join(", ")}` : "";
  const suffix = lifecycleSuffix(e);
  return `- \`${e.type}\` [${escapeLinkText(e.title)}](${encodePath(e.relPath)})${kw}${suffix}`;
}

function lifecycleSuffix(e: ScannedNote): string {
  const bits: string[] = [];
  const caution = new Set([
    "superseded",
    "stale-suspect",
    "archived",
    "deprecated",
  ]);
  if (e.status && caution.has(e.status)) bits.push(e.status);
  return bits.length ? ` _(${bits.join(" · ")})_` : "";
}

function gist(noteCount: number, wingCount: number): string {
  return `> ${noteCount} ${plural(noteCount, "note")} across ${wingCount} ${plural(wingCount, "wing")}. Generated by \`mage index\`.`;
}

function plural(n: number, word: string): string {
  return n === 1 ? word : `${word}s`;
}

function escapeLinkText(s: string): string {
  return s.replace(/\]/g, "\\]");
}

/**
 * Make a relative path safe as a markdown link destination. Percent-encode each
 * segment (preserving `/` separators) AND escape parens — `encodeURIComponent`
 * leaves `(`/`)` raw, which would close the markdown link early.
 */
function encodePath(p: string): string {
  return p
    .split("/")
    .map((seg) =>
      encodeURIComponent(seg).replace(/\(/g, "%28").replace(/\)/g, "%29"),
    )
    .join("/");
}

// ─── idempotency ─────────────────────────────────────────────────────────────

async function cleanGeneratedWingIndexes(
  root: string,
  keepWings: string[],
): Promise<void> {
  const keep = new Set(keepWings.map((w) => `_index.${w}.md`));
  let entries: import("node:fs").Dirent[];
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isFile() || !/^_index\..+\.md$/.test(e.name) || keep.has(e.name))
      continue;
    const p = join(root, e.name);
    try {
      const content = await readFile(p, "utf8");
      if (content.includes(GEN_MARKER)) await rm(p);
    } catch {
      /* leave files we can't read */
    }
  }
}
