import { readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { logger } from "../logger.js";
import { updateGraphColorGroups } from "../obsidian.js";
import {
  INDEX_FILE,
  type HubProject,
  MEMORY_FILE,
  readHubMetadata,
  requireDocsRoot,
} from "../paths.js";
import { type ScannedNote, scanNotes } from "../scan.js";

const GEN_MARKER = "<!-- GENERATED by `mage index` — do not edit by hand. -->";
/** Below these bounds the index stays a single flat file; past them it goes hierarchical. */
const FLAT_MAX_WINGS = 4;
const FLAT_MAX_NOTES = 20;

export interface IndexOptions {
  /** Where to look for the knowledge base (default cwd; walks up for in-repo). */
  dir?: string;
}

export interface IndexResult {
  root: string;
  noteCount: number;
  wings: string[];
  hierarchical: boolean;
  written: string[];
}

/**
 * Generate the hierarchical INDEX (the always-loaded "closet"). Deterministic
 * and idempotent: same notes → identical output, re-run → no diff (ADR-0006).
 */
export async function index(opts: IndexOptions = {}): Promise<IndexResult> {
  const resolved = await requireDocsRoot(opts.dir);
  const root = resolved.root;

  const entries = await scanNotes(root);
  // Wings are the UNION of every note's tag-wings (multi-home, ADR-0012 §5).
  const wings = [...new Set(entries.flatMap((e) => e.wings.map((w) => w.wing)))].sort();
  const hierarchical = wings.length > FLAT_MAX_WINGS || entries.length > FLAT_MAX_NOTES;

  // Registry decorates the index (code-repo pointers, in-repo-member pointers) but
  // never drives grouping — notes are found/grouped by tag/wing alone (ADR-0011 §3).
  const hubMeta = resolved.kind === "hub" ? await readHubMetadata(root) : null;
  const registry = buildRegistryView(hubMeta?.projects ?? []);

  // Remove stale generated per-wing index files (idempotency across mode flips).
  await cleanGeneratedWingIndexes(root, hierarchical ? wings : []);

  const written: string[] = [];
  if (hierarchical) {
    await writeFile(join(root, INDEX_FILE), renderRootHierarchical(entries, wings, registry));
    written.push(INDEX_FILE);
    for (const wing of wings) {
      const file = `_index.${wing}.md`;
      await writeFile(join(root, file), renderWing(wing, wingEntries(entries, wing), registry));
      written.push(file);
    }
  } else {
    await writeFile(join(root, INDEX_FILE), renderFlat(entries, wings, registry));
    written.push(INDEX_FILE);
  }

  // The Claude Code adapter twin (ADR-0032/0033): always emit MEMORY.md at the
  // docs-root top so CC's `autoMemoryDirectory` auto-loads it. For a single-wing
  // (or flat) KB it folds the per-note list inline (rich recall, CC self-bounds at
  // 25KB); for a multi-wing hierarchical KB it stays the bounded wings-map twin.
  await writeFile(join(root, MEMORY_FILE), renderMemory(entries, wings, hierarchical, registry));
  written.push(MEMORY_FILE);

  // Keep the Obsidian graph colored by wing (no-op without .obsidian/graph.json).
  await updateGraphColorGroups(root, wings);

  logger.success(
    `Indexed ${entries.length} note(s) across ${wings.length} wing(s) → ${written.length} file(s) (${
      hierarchical ? "hierarchical" : "flat"
    }).`,
  );
  for (const w of written) logger.detail(w);
  return { root, noteCount: entries.length, wings, hierarchical, written };
}

// ─── registry decoration (ADR-0011 §3, ADR-0012 §2) ──────────────────────────

interface RegistryView {
  /** wing name → code-repo reference (url ?? path), for heading decoration. */
  decorationByWing: Map<string, string>;
  /** in-repo members: notes live in their own repo; shown as a pointer, never empty. */
  inRepoMembers: Array<{ name: string; codeRepoPath: string }>;
}

function buildRegistryView(projects: HubProject[]): RegistryView {
  const decorationByWing = new Map<string, string>();
  for (const p of projects) decorationByWing.set(p.name, p.code_repo_url || p.code_repo_path);
  const inRepoMembers = projects
    .filter((p) => p.storage === "repo-owned")
    .map((p) => ({ name: p.name, codeRepoPath: p.code_repo_path }))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return { decorationByWing, inRepoMembers };
}

/** Notes tagged under `wing` (multi-home: a note appears under every tag-wing). */
function wingEntries(entries: ScannedNote[], wing: string): ScannedNote[] {
  return entries.filter((e) => e.wings.some((w) => w.wing === wing));
}

/** The room a note occupies *within a given wing* (not necessarily its primary room). */
function roomForWing(e: ScannedNote, wing: string): string {
  return e.wings.find((w) => w.wing === wing)?.room ?? "";
}

function wingDecoration(reg: RegistryView, wing: string): string {
  const ref = reg.decorationByWing.get(wing);
  return ref ? ` — code repo: \`${ref}\`` : "";
}

/** A satellite section so an in-repo member is visible even with zero hub-owned notes. */
function pushLinkedRepos(lines: string[], reg: RegistryView): void {
  if (reg.inRepoMembers.length === 0) return;
  lines.push("## Linked repositories", "");
  for (const m of reg.inRepoMembers) {
    lines.push(
      `- **${m.name}** — notes live in \`${m.codeRepoPath}/mage\` → open its INDEX (in-repo member)`,
    );
  }
  lines.push("");
}

// ─── rendering ───────────────────────────────────────────────────────────────

function renderFlat(entries: ScannedNote[], wings: string[], reg: RegistryView): string {
  const lines: string[] = [GEN_MARKER, "", "# Index", "", gist(entries.length, wings.length), ""];
  for (const wing of wings) {
    lines.push(`## ${wing}${wingDecoration(reg, wing)}`, "");
    pushRooms(lines, wingEntries(entries, wing), wing);
  }
  const cross = entries.filter((e) => e.wings.length === 0);
  if (cross.length > 0) {
    lines.push("## Cross-cutting", "");
    for (const e of cross) lines.push(closetLine(e));
    lines.push("");
  }
  pushLinkedRepos(lines, reg);
  if (entries.length === 0 && reg.inRepoMembers.length === 0) {
    lines.push("_No notes yet. Add notes under `notes/` and re-run `mage index`._", "");
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function renderRootHierarchical(entries: ScannedNote[], wings: string[], reg: RegistryView): string {
  const lines: string[] = [
    GEN_MARKER,
    "",
    "# Index",
    "",
    gist(entries.length, wings.length),
    "",
    "## Wings",
    "",
  ];
  for (const wing of wings) {
    const we = wingEntries(entries, wing);
    const types = [...new Set(we.map((e) => e.type))].sort().join(", ");
    lines.push(
      `- **${wing}** (${we.length} ${plural(we.length, "note")} · ${types})${wingDecoration(reg, wing)} → [_index.${wing}.md](${encodePath(`_index.${wing}.md`)})`,
    );
  }
  lines.push("");
  const cross = entries.filter((e) => e.wings.length === 0);
  if (cross.length > 0) {
    lines.push("## Cross-cutting", "");
    for (const e of cross) lines.push(closetLine(e));
    lines.push("");
  }
  pushLinkedRepos(lines, reg);
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

/**
 * MEMORY.md content — the Claude Code adapter twin of INDEX.md (ADR-0032/0033).
 * A single-wing (or flat) KB folds the full per-note list inline so CC's launch
 * recall is rich (CC self-bounds the load at 200 lines / 25KB); a multi-wing
 * hierarchical KB stays the bounded wings-map twin (never inline every wing — the
 * unbounded cost ADR-0033 forbids).
 */
function renderMemory(
  entries: ScannedNote[],
  wings: string[],
  hierarchical: boolean,
  reg: RegistryView,
): string {
  const foldInline = !hierarchical || wings.length <= 1;
  return foldInline
    ? renderFlat(entries, wings, reg)
    : renderRootHierarchical(entries, wings, reg);
}

function renderWing(wing: string, entries: ScannedNote[], reg: RegistryView): string {
  const lines: string[] = [
    GEN_MARKER,
    "",
    `# ${wing}${wingDecoration(reg, wing)}`,
    "",
    `> ${entries.length} ${plural(entries.length, "note")}. Part of the [index](INDEX.md).`,
    "",
  ];
  pushRooms(lines, entries, wing);
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

/**
 * Append room-grouped closet lines for one wing (rooms sorted; the no-room group
 * first, unlabeled). A note's room is resolved *per wing* so a multi-homed note
 * sits under the right room in each wing it's listed in.
 */
function pushRooms(lines: string[], entries: ScannedNote[], wing: string): void {
  const roomOf = (e: ScannedNote) => roomForWing(e, wing);
  const rooms = [...new Set(entries.map(roomOf))].sort((a, b) => {
    if (a === "") return -1;
    if (b === "") return 1;
    return a < b ? -1 : a > b ? 1 : 0;
  });
  for (const room of rooms) {
    const group = entries.filter((e) => roomOf(e) === room);
    if (room !== "") lines.push(`### ${room}`, "");
    for (const e of group) lines.push(closetLine(e));
    lines.push("");
  }
}

function closetLine(e: ScannedNote): string {
  const kw = e.keywords.length ? ` — ${e.keywords.join(", ")}` : "";
  return `- \`${e.type}\` [${escapeLinkText(e.title)}](${encodePath(e.relPath)})${kw}${lifecycleSuffix(e)}`;
}

function lifecycleSuffix(e: ScannedNote): string {
  const bits: string[] = [];
  if (e.status && e.status !== "active") bits.push(e.status);
  if (e.lastReviewed) bits.push(`reviewed ${e.lastReviewed}`);
  return bits.length ? ` _(${bits.join(" · ")})_` : "";
}

function gist(noteCount: number, wingCount: number): string {
  return `> ${noteCount} ${plural(noteCount, "note")} across ${wingCount} ${plural(wingCount, "wing")}. Generated by \`mage index\`.`;
}

function plural(n: number, word: string): string {
  return n === 1 ? word : `${word}s`;
}

function escapeLinkText(s: string): string {
  return s.replace(/\]/g, "\\]");
}

/**
 * Make a relative path safe as a markdown link destination. Percent-encode each
 * segment (preserving `/` separators) AND escape parens — `encodeURIComponent`
 * leaves `(`/`)` raw, which would close the markdown link early.
 */
function encodePath(p: string): string {
  return p
    .split("/")
    .map((seg) => encodeURIComponent(seg).replace(/\(/g, "%28").replace(/\)/g, "%29"))
    .join("/");
}

// ─── idempotency ─────────────────────────────────────────────────────────────

async function cleanGeneratedWingIndexes(root: string, keepWings: string[]): Promise<void> {
  const keep = new Set(keepWings.map((w) => `_index.${w}.md`));
  let entries: import("node:fs").Dirent[];
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isFile() || !/^_index\..+\.md$/.test(e.name) || keep.has(e.name)) continue;
    const p = join(root, e.name);
    try {
      const content = await readFile(p, "utf8");
      if (content.includes(GEN_MARKER)) await rm(p);
    } catch {
      /* leave files we can't read */
    }
  }
}
