import { confirm, select } from "@inquirer/prompts";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { writeAgentsMd } from "../agents-md.js";
import { getRemoteOriginUrl, gitInit, hasGh, isGitRepo } from "../git.js";
import { ensureGitignored } from "../gitignore.js";
import { logger } from "../logger.js";
import { writeObsidianScaffold } from "../obsidian.js";
import {
  ARCHIVE_DIR,
  DECISIONS_DIR,
  type HubMetadata,
  IDENTITY_FILE,
  INDEX_FILE,
  type MageMetadata,
  METADATA_SCHEMA,
  NOTES_DIR,
  PROJECTS_DIR,
  WORK_DIR,
  absolutePath,
  codeRepoDocsRoot,
  exists,
  hubMetadataPath,
  looksLikeHub,
  metadataPath,
  writeHubMetadata,
  writeMetadata,
} from "../paths.js";
import { run } from "../shell.js";

export type InitMode = "in-repo" | "hub";
export type InitVisibility = "private" | "public" | "local";

export interface InitOptions {
  /** in-repo vs standalone hub. If absent, detected from the cwd (git → in-repo). */
  mode?: InitMode;
  /** Hub mode: hub name OR path (bare name → ./<name>; a path → that path). */
  name?: string;
  /** Hub mode: explicit hub directory override (wins over `name`). */
  dir?: string;
  /** Hub mode: git provisioning visibility. */
  visibility?: InitVisibility;
  /** Hub mode + private/public: GitHub owner. Auto-detected via `gh api user` if absent. */
  owner?: string;
  /** in-repo mode: project name (default: basename of code repo). */
  project?: string;
  /** Non-interactive: fail rather than prompt. */
  yes?: boolean;
  /** The directory to operate in (the code repo, or where a hub is created). Default = cwd. */
  codeRepo?: string;
}

export interface InitResult {
  mode: InitMode;
  codeRepo: string;
  project: string;
  hubDir: string | null;
  hubRepoUrl: string | null;
}

const SEED_INDEX = `<!-- GENERATED by \`mage index\` — do not edit by hand. -->

# Index

_No notes yet. Add notes under \`${NOTES_DIR}/\` and run \`mage index\` to populate this index._
`;

export async function init(opts: InitOptions = {}): Promise<InitResult> {
  const cwd = absolutePath(opts.codeRepo ?? process.cwd());
  if (!(await exists(cwd))) {
    throw new Error(`Path does not exist: ${cwd}`);
  }

  const mode = await resolveMode(opts, cwd);

  if (mode === "in-repo") {
    // The cwd is already a hub root (e.g. re-running init after a standalone hub
    // git-init'd this dir) — refuse rather than nest an in-repo KB inside it.
    if (await looksLikeHub(cwd)) {
      throw new Error(
        `${cwd} is already a mage hub. Use \`mage link\` to add a code repo, not \`mage init\`.`,
      );
    }
    const project = opts.project ?? basename(cwd);
    // Refuse to re-init if code-repo metadata already present.
    if (await exists(metadataPath(cwd))) {
      throw new Error(
        `${metadataPath(cwd)} already exists. ` +
          "This code repo already has a mage knowledge base. " +
          "Run `mage link <hub>` to add a hub reference, or remove mage/metadata.json first.",
      );
    }
    await initInRepo(cwd, project);
    return { mode, codeRepo: cwd, project, hubDir: null, hubRepoUrl: null };
  }

  return initHubFlow(cwd, opts);
}

// ─── mode resolution (detection-first, ADR-0012 §3) ────────────────────────

async function resolveMode(opts: InitOptions, cwd: string): Promise<InitMode> {
  if (opts.mode) return opts.mode;
  // A name or explicit dir implies a hub location.
  if (opts.name || opts.dir) return "hub";
  // Non-interactive: detect — inside a git repo → in-repo, else a standalone hub.
  if (opts.yes) return (await isGitRepo(cwd)) ? "in-repo" : "hub";
  const inGit = await isGitRepo(cwd);
  return (await select<InitMode>({
    message: "Where should the knowledge base live?",
    choices: [
      { name: "In this repo   (recommended inside a code repo)", value: "in-repo" },
      { name: "Standalone hub (recommended for multi-repo / non-code knowledge)", value: "hub" },
    ],
    default: inGit ? "in-repo" : "hub",
  })) as InitMode;
}

async function resolveVisibility(opts: InitOptions): Promise<InitVisibility> {
  if (opts.visibility) return opts.visibility;
  if (opts.yes) return "local";
  const v = (await select<InitVisibility>({
    message: "Hub visibility?",
    choices: [
      {
        name: "private  (GitHub repo, recommended for strategy/customer/work content)",
        value: "private",
      },
      { name: "public   (GitHub repo, for OSS design knowledge)", value: "public" },
      { name: "local    (no GitHub repo — local-only)", value: "local" },
    ],
    default: "private",
  })) as InitVisibility;
  return v;
}

// ─── shared vault scaffolding ──────────────────────────────────────────────

/**
 * Create the core vault subdirs (notes/, work/, decisions/, archive/) with
 * .gitkeep placeholders and a seed INDEX.md. `artifacts/` and `.learnings/`
 * are created lazily (by work + /learn) and are git-ignored.
 */
async function scaffoldVaultDirs(docsRoot: string): Promise<void> {
  for (const d of [NOTES_DIR, WORK_DIR, DECISIONS_DIR, ARCHIVE_DIR]) {
    await mkdir(join(docsRoot, d), { recursive: true });
    await writeFile(join(docsRoot, d, ".gitkeep"), "");
  }
  await writeFile(join(docsRoot, INDEX_FILE), SEED_INDEX);
}

// ─── in-repo init ────────────────────────────────────────────────────────

async function initInRepo(codeRepo: string, project: string): Promise<void> {
  const docsRoot = codeRepoDocsRoot(codeRepo);
  await mkdir(docsRoot, { recursive: true });
  await scaffoldVaultDirs(docsRoot);
  await writeObsidianScaffold(docsRoot);

  const meta: MageMetadata = {
    schema: METADATA_SCHEMA,
    mode: "in-repo",
    project,
    hub_path: null,
    hub_repo: null,
    hub_refs: [],
    linked_at: nowIso(),
  };
  await writeMetadata(codeRepo, meta);
  logger.success(`Wrote ${metadataPath(codeRepo)}`);

  // Git-ignore raw artifacts + pre-promotion scratch + the cockpit (ADR-0020 §6:
  // dashboard.html embeds `.metrics` churn, so it must never be committed); track
  // everything else (ADR-0003).
  const added = await ensureGitignored(codeRepo, [
    "mage/**/artifacts/",
    "mage/.learnings/",
    "mage/.metrics/",
    "mage/dashboard.html",
  ]);
  if (added.length > 0) logger.detail(`Added .gitignore patterns: ${added.join(", ")}`);

  // Portable navigation contract for any agent (AGENTS.md + CLAUDE.md shim).
  await writeAgentsMd(codeRepo, { kind: "repo", mode: "in-repo", docsRel: "mage" });

  logger.blank();
  logger.success(`Initialized in-repo mage knowledge base for project '${project}'.`);
  logger.detail(`Knowledge base: ${docsRoot}`);
  logger.detail(`Add notes under notes/, capture work in work/<slug>/, then run \`mage index\`.`);
  printPluginSkillsHint();
  logger.blank();
  logger.info("Suggested commit (run yourself; mage never auto-commits):");
  logger.detail(`  git -C ${codeRepo} add mage AGENTS.md CLAUDE.md .gitignore`);
  logger.detail(`  git -C ${codeRepo} commit -m "feat: mage init (in-repo, project=${project})"`);
}

// ─── standalone hub init (ADR-0012 §3) ─────────────────────────────────────

/**
 * Resolve the hub location, guard it, and create a STANDALONE hub (projects: []).
 * No code repo is registered and no project vault is scaffolded — link code
 * repos afterwards with `mage link`. Stays suggest-only (never runs a commit).
 */
async function initHubFlow(cwd: string, opts: InitOptions): Promise<InitResult> {
  // Location: explicit --dir wins; else a bare name → ./<name> and a path → that
  // path (like `git init`/`npm init`); else the current dir (standalone in place).
  const hubDir = opts.dir ? absolutePath(opts.dir) : opts.name ? absolutePath(opts.name) : cwd;
  const hubName = basename(hubDir);

  if (await isGitRepo(cwd)) {
    logger.warn(
      `Creating a mage hub while inside a git repo (${cwd}). ` +
        "If you meant a knowledge base that lives with this code, re-run with --in-repo.",
    );
  }
  if (await looksLikeHub(hubDir)) {
    throw new Error(
      `${hubDir} is already a mage hub. Use \`mage link\` to add projects, or pick a new location.`,
    );
  }
  if (await exists(hubDir)) {
    const entries = await readdir(hubDir);
    if (entries.length > 0) {
      if (hubDir !== cwd) throw new Error(`Target hub directory not empty: ${hubDir}`);
      // Scaffolding into a non-empty current dir: confirm (or require -y).
      if (!opts.yes) {
        const ok = await confirm({
          message: `Scaffold a mage hub into the current non-empty directory ${hubDir}?`,
          default: false,
        });
        if (!ok) throw new Error("Aborted — no changes made.");
      }
    }
  }

  const visibility = await resolveVisibility(opts);
  const hubRepoUrl = await initStandaloneHub({ hubDir, hubName, visibility, owner: opts.owner });
  return { mode: "hub", codeRepo: cwd, project: hubName, hubDir, hubRepoUrl };
}

interface HubArgs {
  hubDir: string;
  hubName: string;
  visibility: InitVisibility;
  owner: string | undefined;
}

/**
 * Provision the hub git repo (local or GitHub), scaffold its structure, and
 * write its registry (`projects: []`). Returns the hub's remote URL (or local
 * path for local-only). git *provisioning* (init / gh repo create) is allowed;
 * COMMITS are only ever suggested (the "mage never runs git" invariant is about
 * commits — ADR-0012 §3).
 */
async function initStandaloneHub(args: HubArgs): Promise<string> {
  const { hubDir, hubName, visibility } = args;

  let hubRepoUrl: string;
  if (visibility === "local") {
    await mkdir(hubDir, { recursive: true });
    await gitInit(hubDir);
    hubRepoUrl = hubDir; // no remote; use local path as identifier
    logger.success(`Initialized local hub at ${hubDir}`);
  } else {
    if (!(await hasGh())) {
      throw new Error(
        `Visibility '${visibility}' requires the GitHub CLI ('gh'). ` +
          "Install from https://cli.github.com/ or pick --local.",
      );
    }
    const owner = args.owner ?? (await detectGhOwner());
    if (!owner) {
      throw new Error("Could not detect GitHub owner via `gh api user`. Pass --owner <user-or-org>.");
    }
    const fullName = `${owner}/${hubName}`;
    await mkdir(dirname(hubDir), { recursive: true });
    logger.step(`Creating ${visibility} GitHub repo ${fullName}…`);
    await run("gh", ["repo", "create", fullName, `--${visibility}`, "--clone"], {
      cwd: dirname(hubDir),
      throwOnError: true,
      inherit: true,
    });
    logger.success(`Cloned to ${hubDir}`);
    hubRepoUrl = (await getRemoteOriginUrl(hubDir)) ?? `https://github.com/${fullName}.git`;
  }

  await scaffoldHubStructure(hubDir, hubName);
  logger.success(`Scaffolded hub structure at ${hubDir}`);

  const hubMeta: HubMetadata = {
    schema: METADATA_SCHEMA,
    name: hubName,
    created_at: nowIso(),
    projects: [],
  };
  await writeHubMetadata(hubDir, hubMeta);
  logger.success(`Wrote ${hubMetadataPath(hubDir)}`);

  const added = await ensureGitignored(hubDir, [
    "**/artifacts/",
    ".learnings/",
    "**/.learnings/",
    ".metrics/",
    "**/.metrics/",
    // The cockpit embeds `.metrics` churn (ADR-0020 §6) — never commit it.
    "dashboard.html",
  ]);
  if (added.length > 0) logger.detail(`Added .gitignore patterns: ${added.join(", ")}`);

  await writeAgentsMd(hubDir, { kind: "hub", docsRel: "." });

  logger.blank();
  logger.success(`Initialized standalone mage hub '${hubName}'.`);
  logger.detail(`Link a code repo with: mage link ${hubDir}`);
  printPluginSkillsHint();
  logger.blank();
  logger.info("Suggested commits (run yourself; mage never auto-commits):");
  logger.detail(`  git -C ${hubDir} add .`);
  logger.detail(`  git -C ${hubDir} commit -m "feat: mage hub '${hubName}'"`);
  if (visibility !== "local") {
    logger.detail(`  git -C ${hubDir} push -u origin main`);
  }

  return hubRepoUrl;
}

async function scaffoldHubStructure(hubDir: string, hubName: string): Promise<void> {
  // System-level vault dirs (notes/work/decisions/archive + seed INDEX).
  await scaffoldVaultDirs(hubDir);

  // projects/ registry dir.
  await mkdir(join(hubDir, PROJECTS_DIR), { recursive: true });
  await writeFile(join(hubDir, PROJECTS_DIR, ".gitkeep"), "");

  // IDENTITY.md — the hub's "who am I" page.
  await writeFile(
    join(hubDir, IDENTITY_FILE),
    `# ${hubName} — IDENTITY

> The hub's identity: what system this knowledge base spans, who owns it, and
> the conventions agents should follow. Read this first if you're new to the hub.

## What this hub spans
TODO — the repos/services/people this brain covers.

## Owner
TODO

## Conventions
TODO — naming, wings in use, voice.
`,
  );

  // Obsidian vault config at the hub root (the hub IS the vault).
  await writeObsidianScaffold(hubDir);
}

// ─── utilities ───────────────────────────────────────────────────────────

/**
 * Point the user at mage's skills, which ship as a Claude Code plugin (the
 * `mage:` namespace keeps names clean — `mage:learn`, `mage:distill`, …). Install
 * is user-driven; mage never runs the slash commands for you.
 */
function printPluginSkillsHint(): void {
  logger.blank();
  logger.info("mage's skills (Claude Code) — add the marketplace, then install the group:");
  logger.detail("  /plugin marketplace add Sumit1993/mage-memory");
  logger.detail("  /plugin install mage@mage");
}

async function detectGhOwner(): Promise<string | null> {
  const r = await run("gh", ["api", "user", "--jq", ".login"]);
  return r.code === 0 ? r.stdout.trim() : null;
}

function nowIso(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
}
