import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { logger } from "../logger.js";
import { absolutePath, resolveDocsRoot } from "../paths.js";
import { type ScannedNote, scanNotes } from "../scan.js";

const GEN_MARKER = "<!-- GENERATED by `mage skills` — do not edit by hand. -->";
/** Broadest portable coverage: project-local skill dirs read by Claude + the agent-skills CLI. */
const TARGET_AGENT_DIRS = [".claude/skills", ".agents/skills"];
const WING_PREFIX = "mage-wing-";
/** Note types worth surfacing as the auto-loaded "nudge" for a wing. */
const NUDGE_TYPES = new Set(["playbook", "gotcha", "interface", "tooling", "relationship", "topology"]);

export interface SkillsOptions {
  dir?: string;
}

export interface SkillsResult {
  repo: string;
  wings: string[];
  written: string[];
}

/**
 * Generate one auto-loaded skill per wing (ADR-0006). Each wing skill is the
 * wing's procedural entry point: it points at the wing's index + notes and
 * surfaces its playbooks/gotchas. Written into project-local agent skill dirs
 * and marked GENERATED so regeneration never clobbers hand-authored skills.
 */
export async function skills(opts: SkillsOptions = {}): Promise<SkillsResult> {
  const start = absolutePath(opts.dir ?? process.cwd());
  const resolved = await resolveDocsRoot(start);
  if (!resolved) {
    throw new Error(`No mage knowledge base found at or above ${start}. Run \`mage init\` first.`);
  }
  const { root, repo } = resolved;
  const docsRel = toRel(relative(repo, root));

  const notes = await scanNotes(root);
  // Wings are the UNION of every note's tag-wings; a multi-homed note's skill is
  // cross-listed into each tagged wing (consistency with `mage index`, ADR-0012 §5).
  const wings = [...new Set(notes.flatMap((n) => n.wings.map((w) => w.wing)))].sort();

  const written: string[] = [];
  for (const base of TARGET_AGENT_DIRS) {
    const skillsRoot = join(repo, base);
    await cleanGeneratedWingSkills(skillsRoot, wings);
    for (const wing of wings) {
      const dir = join(skillsRoot, `${WING_PREFIX}${wing}`);
      await mkdir(dir, { recursive: true });
      await writeFile(
        join(dir, "SKILL.md"),
        renderWingSkill(wing, notes.filter((n) => n.wings.some((w) => w.wing === wing)), docsRel),
      );
      written.push(join(base, `${WING_PREFIX}${wing}`, "SKILL.md"));
    }
  }

  if (wings.length === 0) {
    logger.warn("No wings found (no notes tagged `#<wing>/...`). Nothing to generate.");
  } else {
    logger.success(`Generated ${wings.length} wing skill(s) × ${TARGET_AGENT_DIRS.length} target dir(s).`);
    for (const w of written) logger.detail(w);
  }
  return { repo, wings, written };
}

function renderWingSkill(wing: string, notes: ScannedNote[], docsRel: string): string {
  const indexPath = docsRel === "." ? "INDEX.md" : `${docsRel}/INDEX.md`;
  const wingIndex = docsRel === "." ? `_index.${wing}.md` : `${docsRel}/_index.${wing}.md`;
  const nudges = notes.filter((n) => NUDGE_TYPES.has(n.type)).slice(0, 10);

  const out: string[] = [
    "---",
    `name: ${WING_PREFIX}${wing}`,
    `description: Knowledge and procedures for the ${wing} wing of this repo's mage knowledge base — playbooks, gotchas, interfaces, and where to find more. Load when working on ${wing}.`,
    "---",
    "",
    GEN_MARKER,
    "",
    `# ${wing}`,
    "",
    `Procedural entry point for the **${wing}** wing. mage notes hold the facts; this skill points you at them and surfaces the ${wing}-specific procedures and gotchas so you don't repeat mistakes.`,
    "",
    "## Where the knowledge is",
    "",
    `- Start at the index: \`${indexPath}\` — this wing's detail lives in \`${wingIndex}\` when the index is hierarchical.`,
    "- Open only the notes a task touches; follow their `[text](path.md)` links.",
    "- Treat notes as point-in-time: verify `status: stale-suspect` or stale `last_reviewed` notes against the current code before relying on them.",
    "",
  ];
  if (nudges.length > 0) {
    out.push(`## ${wing} playbooks & gotchas`, "");
    for (const n of nudges) out.push(`- \`${n.type}\` ${n.title} — \`${n.relPath}\``);
    out.push("");
  } else {
    out.push(
      `_No playbook/gotcha/interface notes tagged \`#${wing}\` yet — capture them with \`/mage-learn\`._`,
      "",
    );
  }
  out.push(
    "## Capture",
    "",
    "When you learn something durable in this wing, capture it with `/mage-learn` (insight + procedure + pointers — never a copy of the source), then run `mage index` and `mage skills`.",
    "",
  );
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

async function cleanGeneratedWingSkills(skillsRoot: string, keepWings: string[]): Promise<void> {
  const keep = new Set(keepWings.map((w) => `${WING_PREFIX}${w}`));
  let entries: import("node:fs").Dirent[];
  try {
    entries = await readdir(skillsRoot, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory() || !e.name.startsWith(WING_PREFIX) || keep.has(e.name)) continue;
    const skillFile = join(skillsRoot, e.name, "SKILL.md");
    try {
      const content = await readFile(skillFile, "utf8");
      if (content.includes(GEN_MARKER)) await rm(join(skillsRoot, e.name), { recursive: true, force: true });
    } catch {
      /* leave dirs that aren't ours */
    }
  }
}

function toRel(p: string): string {
  return p === "" ? "." : p.split(/[\\/]/).join("/");
}
