import type { Dirent } from "node:fs";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { logger } from "../logger.js";
import {
  foldRollup,
  type SkillMetricRow,
  summarize,
  writeRollup,
} from "../metrics/rollup.js";
import { absolutePath, LEARNINGS_DIR, resolveDocsRoot } from "../paths.js";
import { type ScannedNote, scanNotes } from "../scan.js";

const GEN_MARKER = "<!-- GENERATED by `mage skills` — do not edit by hand. -->";
/** Broadest portable coverage: project-local skill dirs read by Claude + the agent-skills CLI. */
const TARGET_AGENT_DIRS = [".claude/skills", ".agents/skills"];
const WING_PREFIX = "mage-wing-";
/** Note types worth surfacing as the auto-loaded "nudge" for a wing. */
const NUDGE_TYPES = new Set(["playbook", "gotcha", "interface", "tooling", "relationship", "topology"]);

export interface SkillsOptions {
  dir?: string;
  /** Read-only context-match metrics mode (ADR-0016 §1). Never regenerates skills. */
  metrics?: boolean;
  /** Emit the metric rows as JSON instead of the plain-text table (metrics mode only). */
  json?: boolean;
  /** Silent fold (the Stop-hook path): fold + write the rollup, print nothing. */
  quiet?: boolean;
}

export interface SkillsResult {
  repo: string;
  wings: string[];
  /** Generated `mage-wing-*` skill paths. */
  written: string[];
  /** Advisory metric rows (metrics mode only; absent for skill generation). */
  metricsRows?: SkillMetricRow[];
}

/**
 * Generate one auto-loaded skill per wing (ADR-0006). Each wing skill is the
 * wing's procedural entry point: it points at the wing's index + notes and
 * surfaces its playbooks/gotchas. Written into project-local agent skill dirs
 * and marked GENERATED so regeneration never clobbers hand-authored skills.
 */
export async function skills(opts: SkillsOptions = {}): Promise<SkillsResult> {
  const start = absolutePath(opts.dir ?? process.cwd());
  if (opts.metrics) return skillsMetrics(start, opts);

  const resolved = await resolveDocsRoot(start);
  if (!resolved) {
    throw new Error(`No mage knowledge base found at or above ${start}. Run \`mage init\` first.`);
  }
  const { root, repo } = resolved;
  const docsRel = toRel(relative(repo, root));

  const notes = await scanNotes(root);
  // Wings are the UNION of every note's tag-wings; a multi-homed note's skill is
  // cross-listed into each tagged wing (consistency with `mage index`, ADR-0012 §5).
  const wings = [...new Set(notes.flatMap((n) => n.wings.map((w) => w.wing)))].sort();

  const written: string[] = [];
  for (const base of TARGET_AGENT_DIRS) {
    const skillsRoot = join(repo, base);
    await cleanGeneratedWingSkills(skillsRoot, wings);
    for (const wing of wings) {
      const dir = join(skillsRoot, `${WING_PREFIX}${wing}`);
      await mkdir(dir, { recursive: true });
      await writeFile(
        join(dir, "SKILL.md"),
        renderWingSkill(wing, notes.filter((n) => n.wings.some((w) => w.wing === wing)), docsRel),
      );
      written.push(join(base, `${WING_PREFIX}${wing}`, "SKILL.md"));
    }
  }

  if (wings.length === 0) {
    logger.warn("No wings found (no notes tagged `#<wing>/...`). Nothing to generate.");
  } else {
    logger.success(`Generated ${wings.length} wing skill(s) × ${TARGET_AGENT_DIRS.length} target dir(s).`);
    for (const w of written) logger.detail(w);
  }
  return { repo, wings, written };
}

/**
 * Read-only context-match metrics (ADR-0016 §1). This is ALSO the Stop-hook path
 * (`mage skills --metrics --quiet`), so the fold MUST NEVER throw to the host: the
 * whole branch — including resolveDocsRoot, which can reject on fs errors — fails
 * open. metrics mode is READ-ONLY: it never regenerates wing skills.
 *
 *  - no KB found → print "No knowledge base found." (unless --quiet) and return empty.
 *  - --quiet     → fold + write the rollup silently (no output): the Stop fold.
 *  - --json      → print the summarized rows as JSON.
 *  - else        → print a plain-text table (or the empty-state line).
 */
async function skillsMetrics(start: string, opts: SkillsOptions): Promise<SkillsResult> {
  const resolved = await resolveDocsRoot(start).catch(() => null);
  if (!resolved) {
    if (!opts.quiet) logger.info("No knowledge base found.");
    return { repo: start, wings: [], written: [], metricsRows: [] };
  }
  const { root, repo } = resolved;

  // Fold + write are wrapped so the Stop hook survives ANY fs/parse error.
  let rows: SkillMetricRow[] = [];
  try {
    const learningsDir = join(root, LEARNINGS_DIR);
    const rollup = await foldRollup(root, learningsDir, repo);
    await writeRollup(root, rollup);
    rows = summarize(rollup);
  } catch {
    /* fail-open: the Stop-hook metrics fold must never break the host */
  }

  if (opts.quiet) return { repo, wings: [], written: [], metricsRows: rows };
  if (opts.json) console.log(JSON.stringify(rows, null, 2));
  else renderMetricsTable(rows);
  return { repo, wings: [], written: [], metricsRows: rows };
}

/** Plain-text advisory table (worst-first), mirroring `mage list`'s table style. */
function renderMetricsTable(rows: SkillMetricRow[]): void {
  if (rows.length === 0) {
    logger.info("No skill-load metrics yet.");
    return;
  }
  const skillWidth = Math.max(5, ...rows.map((r) => r.skill.length));
  const header = `${"SKILL".padEnd(skillWidth)}  LOADS  MATCH-RATE  STATUS`;
  logger.info(header);
  logger.detail("─".repeat(header.length));
  for (const r of rows) {
    const rate = `${(r.matchRate * 100).toFixed(0)}%`;
    logger.info(
      `${r.skill.padEnd(skillWidth)}  ${String(r.loads).padStart(5)}  ${rate.padStart(10)}  ${r.status}`,
    );
    logger.detail(`dims paths=${r.dims.paths} keywords=${r.dims.keywords} wing=${r.dims.wing}`);
  }
}

function renderWingSkill(wing: string, notes: ScannedNote[], docsRel: string): string {
  const indexPath = docsRel === "." ? "INDEX.md" : `${docsRel}/INDEX.md`;
  const wingIndex = docsRel === "." ? `_index.${wing}.md` : `${docsRel}/_index.${wing}.md`;
  const nudges = notes.filter((n) => NUDGE_TYPES.has(n.type)).slice(0, 10);

  const out: string[] = [
    "---",
    `name: ${WING_PREFIX}${wing}`,
    `description: Knowledge and procedures for the ${wing} wing of this repo's mage knowledge base — playbooks, gotchas, interfaces, and where to find more. Load when working on ${wing}.`,
    "---",
    "",
    GEN_MARKER,
    "",
    `# ${wing}`,
    "",
    `Procedural entry point for the **${wing}** wing. mage notes hold the facts; this skill points you at them and surfaces the ${wing}-specific procedures and gotchas so you don't repeat mistakes.`,
    "",
    "## Where the knowledge is",
    "",
    `- Start at the index: \`${indexPath}\` — this wing's detail lives in \`${wingIndex}\` when the index is hierarchical.`,
    "- Open only the notes a task touches; follow their `[text](path.md)` links.",
    "- Treat notes as point-in-time: verify `status: stale-suspect` or stale `last_reviewed` notes against the current code before relying on them.",
    "",
  ];
  if (nudges.length > 0) {
    out.push(`## ${wing} playbooks & gotchas`, "");
    for (const n of nudges) out.push(`- \`${n.type}\` ${n.title} — \`${n.relPath}\``);
    out.push("");
  } else {
    out.push(
      `_No playbook/gotcha/interface notes tagged \`#${wing}\` yet — capture them with \`mage:learn\`._`,
      "",
    );
  }
  out.push(
    "## Capture",
    "",
    "When you learn something durable in this wing, capture it with `mage:learn` (insight + procedure + pointers — never a copy of the source), then run `mage index` and `mage skills`.",
    "",
  );
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

async function cleanGeneratedWingSkills(skillsRoot: string, keepWings: string[]): Promise<void> {
  const keep = new Set(keepWings.map((w) => `${WING_PREFIX}${w}`));
  let entries: Dirent[];
  try {
    entries = await readdir(skillsRoot, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory() || !e.name.startsWith(WING_PREFIX) || keep.has(e.name)) continue;
    const skillFile = join(skillsRoot, e.name, "SKILL.md");
    try {
      const content = await readFile(skillFile, "utf8");
      if (content.includes(GEN_MARKER)) await rm(join(skillsRoot, e.name), { recursive: true, force: true });
    } catch {
      /* leave dirs that aren't ours */
    }
  }
}

function toRel(p: string): string {
  return p === "" ? "." : p.split(/[\\/]/).join("/");
}
