import { readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";

import { type ChosenHubRootSource, chosenHubRoot, verifyHubArrival } from "./hub-url.js";
import { exists, hubMetadataPath, isUnder, looksLikeHub, META_FILE, PROJECTS_DIR } from "./path-guards.js";
import { type Genre, resolveGenreOverrides } from "./scanner/genre-map.js";

// ADR-0043: isUnder/looksLikeHub/exists/hubMetadataPath/PROJECTS_DIR/META_FILE now
// live in the leaf module path-guards.ts (hub-url.ts needs them without importing
// this file, which itself imports hub-url.ts). Re-exported here so every existing
// `from "./paths.js"` import keeps working unchanged.
export { exists, hubMetadataPath, isUnder, looksLikeHub, META_FILE, PROJECTS_DIR };
export { chosenHubRoot, hubsRoot, type ChosenHubRoot, type ChosenHubRootSource } from "./hub-url.js";

// ─── path constants ──────────────────────────────────────────────────────
/** The knowledge-base (KB) dir nested in a code repo (in-repo and hybrid modes). */
export const META_DIR = "mage";
export const ARCHIVE_DIR = "archive";

// KB layout (inside a docs root, whether a repo `mage/` or a hub root).
export const NOTES_DIR = "notes";
export const WORK_DIR = "work";
export const DECISIONS_DIR = "decisions";
export const INDEX_FILE = "INDEX.md";
/**
 * The Claude Code adapter twin of INDEX.md, emitted at the docs-root top so CC's
 * `autoMemoryDirectory` auto-loads it at launch (ADR-0032/0033). Generated by
 * `mage index`; reserved like INDEX_FILE so the scanner never ingests it as a note.
 */
export const MEMORY_FILE = "MEMORY.md";
export const IDENTITY_FILE = "IDENTITY.md";
/**
 * The single git-ignored home for ALL machine-written transient state (ADR-0025).
 * Every regenerable/rebuildable runtime artifact lives under `<docsRoot>/.mage/`,
 * via the LEARNINGS_DIR/METRICS_DIR/STAGING_DIR leaves below — one gitignore line,
 * one scan-skip, one doctor probe. New runtime state has exactly one home and is
 * never a new top-level entry at the docs root.
 */
export const STATE_DIR = ".mage";
/** Pre-promotion scratch leaf under STATE_DIR (git-ignored): `.mage/learnings/`. */
export const LEARNINGS_DIR = "learnings";
/** Read-only context-match rollup leaf under STATE_DIR (git-ignored): `.mage/metrics/`. */
export const METRICS_DIR = "metrics";
/**
 * Judged-but-uncommitted lesson drafts of the organic grooming loop — leaf under
 * STATE_DIR (git-ignored): `.mage/staging/` (0.0.12). A third epistemic state
 * between `.mage/learnings/` (raw, auto-pruned) and `notes/` (committed,
 * indexed-live): drafts wait here, OUT of the live index, until `mage groom`
 * promotes them to `notes/`.
 */
export const STAGING_DIR = "staging";
/** Rotated learnings archives (git-ignored, lives inside the learnings leaf). */
export const LEARNINGS_ARCHIVE_DIR = ".archive";
/** Once-per-day age-purge throttle marker (inside the learnings leaf). */
export const LEARNINGS_PURGE_MARKER = ".last-purge";
/** Per-work-unit raw materials dir name (git-ignored wherever it appears). */
export const ARTIFACTS_DIRNAME = "artifacts";
/** Obsidian config dir (Obsidian's own term; not a mage product noun). */
export const OBSIDIAN_DIR = ".obsidian";
/** Git metadata dir (skipped by the scanner). */
export const GIT_DIR = ".git";
/** Dependency dir (skipped by the scanner). */
export const NODE_MODULES_DIR = "node_modules";
/** Build output dir (skipped by ingest enumeration). */
export const DIST_DIR = "dist";
/** Agent-harness skill/config dirs where `mage skills` writes — skipped by the scanner. */
export const CLAUDE_DIR = ".claude";
export const AGENTS_SKILLS_DIR = ".agents";

export const AGENTS_FILE = "AGENTS.md";
export const CLAUDE_FILE = "CLAUDE.md";
export const GITIGNORE_FILE = ".gitignore";

// ─── schema ──────────────────────────────────────────────────────────────
/** Current on-disk schema version — what every writer stamps. */
export const METADATA_SCHEMA = "mage.v2";
/**
 * Prior schema version. Still read leniently and normalized to v2 in memory
 * (Dec 9 migration): never throws on a v1 file. `mage migrate` rewrites eagerly.
 */
export const METADATA_SCHEMA_V1 = "mage.v1";

/**
 * The Gate-2 false-positive allowlist (ADR-0025), folded into `metadata.json` as
 * the `redact` field (was a `.redactignore` file before the state fold). Two kinds
 * of confirmed false positive let a strict, no-`--no-verify` environment override a
 * redaction match without disabling the pre-commit hook:
 *   - `ignore` — path GLOBs (relative to the docs root) whose staged file is not scanned;
 *   - `allow` — exact matched VALUES that are never treated as a secret.
 * Compiled by {@link redactIgnoreFromMetadata} (see redactignore.ts), fed from here.
 */
export interface RedactConfig {
  /** Path globs (docs-root-relative) whose staged files are skipped by Gate-2. */
  ignore?: string[];
  /** Exact matched values to whitelist as confirmed false positives. */
  allow?: string[];
}

/**
 * The self-grooming dial sub-object on metadata (ADR-0019 §7 + ADR-0030).
 *   - `sensitivity` — scales the recurrence gates (low | normal | high); absent ⇒ "normal".
 *   - `autonomy` — how much of the grooming ladder the host agent drains autonomously
 *     (operator | approver | overseer, ADR-0030); absent ⇒ "operator".
 *   - `nudgeThrottleHours` — the backlog-reminder window in hours (ADR-0030); absent ⇒ 4h.
 *   - `crownThreshold` — the pre-registered autonomy keep-rate (0..1) that would justify
 *     raising the default autonomy (ADR-0031 P2 §7); absent ⇒ unset (the reconciler renders
 *     `unset` and never auto-acts). Deliberately UNVALUED until soak data can calibrate it.
 * Every field is optional so an older metadata file (no grooming, or sensitivity-only)
 * still validates; defaults live in the readers (thresholds.ts), not here.
 */
export interface GroomingConfig {
  sensitivity?: "low" | "normal" | "high";
  autonomy?: "operator" | "approver" | "overseer";
  nudgeThrottleHours?: number;
  crownThreshold?: number;
}

/**
 * Code-repo-side metadata. Lives at `<code-repo>/mage/metadata.json`.
 *
 * Three modes (the canonical KB-shape axis):
 *   - "in-repo":  the KB lives at `<code-repo>/mage/`. hub_refs is empty;
 *                 hub_path/hub_repo are null.
 *   - "hybrid":   the KB lives at `<code-repo>/mage/` (same docs root as in-repo)
 *                 AND is registered with one or more external hubs. hub_refs is
 *                 non-empty; hub_path/hub_repo remain null (each hub_ref carries
 *                 its own pair — see {@link HubRef}).
 *   - "external": the KB is hub-owned; docs live at `<hub root>/projects/<project>/`.
 *                 hub_repo/hub_path are populated; hub_refs is empty.
 *
 * ADR-0043 — `hub_repo` is now the AUTHORITATIVE address; `hub_path` is a
 * deprecated fallback read during the transition window. The hub root a
 * (hub_repo, hub_path) pair resolves to is never read off either field
 * directly — every call site derives it through the ONE shared
 * {@link chosenHubRoot} (prefers `hub_repo`, deriving its deterministic local
 * path under `hubsRoot()`; falls back to `hub_path` only when `hub_repo` is
 * absent or fails to canonicalize). See src/hub-url.ts for the derivation
 * rules and src/paths.ts's {@link outOfRepoKbTargets}/`externalDocsRoot` for
 * where it's applied.
 */
export interface MageMetadata {
  schema: string;
  mode: "in-repo" | "hybrid" | "external";
  project: string;
  hub_path: string | null;
  hub_repo: string | null;
  hub_refs: HubRef[];
  linked_at: string;
  /** Self-grooming dial (ADR-0019 §7 + ADR-0030); absent ⇒ sensitivity "normal", autonomy "operator". */
  grooming?: GroomingConfig;
  /** Gate-2 false-positive allowlist (ADR-0025); absent ⇒ no allowances. */
  redact?: RedactConfig;
  /** Custom type-to-genre overrides (ADR-0041 §3). */
  genres?: Record<string, string>;
}

/**
 * One entry in `hub_refs[]`. Present when mode=hybrid — this code repo is
 * registered with one or more external hubs for cross-cutting context.
 */
export interface HubRef {
  hub_path: string;
  hub_repo: string;
  /** Project name as registered in that hub (may differ from code-repo's own project). */
  project: string;
}

/**
 * Hub-side metadata. Lives at `<hub>/metadata.json` (AT THE ROOT, not nested
 * under mage/, because the hub repo is entirely the knowledge base — no
 * segregation namespace needed). The registry of all projects this hub knows about.
 */
export interface HubMetadata {
  schema: string;
  name: string;
  created_at: string;
  projects: HubProject[];
  /** Self-grooming dial (ADR-0019 §7 + ADR-0030); absent ⇒ sensitivity "normal", autonomy "operator". */
  grooming?: GroomingConfig;
  /** Gate-2 false-positive allowlist (ADR-0025); absent ⇒ no allowances. */
  redact?: RedactConfig;
  /** Custom type-to-genre overrides (ADR-0041 §3). */
  genres?: Record<string, string>;
}

export interface HubProject {
  name: string;
  /**
   * "hub-owned" — the project's notes live at `<hub>/projects/<name>/`
   * (the hub has the actual files). Used when the code repo was linked via the
   * external-only flow (no in-repo notes at link time).
   *
   * "repo-owned" — the project's notes live at `<code_repo_path>/mage/` (the code
   * repo owns the files; the hub just registers awareness). Used in hybrid mode.
   */
  storage: "hub-owned" | "repo-owned";
  code_repo_path: string;
  code_repo_url: string;
}

// ─── path helpers ────────────────────────────────────────────────────────

/** Code repo's metadata file. */
export function metadataPath(codeRepo: string): string {
  return join(codeRepo, META_DIR, META_FILE);
}

/**
 * Code repo's docs root — where notes/, decisions/, work/, INDEX.md land when
 * mode=in-repo or mode=hybrid (both store locally in `<code-repo>/mage/`).
 */
export function codeRepoDocsRoot(codeRepo: string): string {
  return join(codeRepo, META_DIR);
}

/** Guard against path traversal via a name that becomes a directory segment. */
export function assertSafeName(name: string, kind: string): void {
  if (!name || name === "." || name === ".." || /[/\\\0]/.test(name)) {
    throw new Error(
      `Unsafe ${kind} '${name}': must not be empty, '.', '..', or contain path separators.`,
    );
  }
}

/** Hub-owned project's directory (no `mage/` nesting at THIS level). */
export function hubProjectPath(hubRoot: string, projectName: string): string {
  assertSafeName(projectName, "project name");
  return join(hubRoot, PROJECTS_DIR, projectName);
}

/**
 * Hub-owned project's docs root — where a project's notes land. FLAT (ADR-0011
 * §6): `projects/<name>/{notes,decisions,…}`, no `mage/` nesting. A project
 * looks like the hub it lives in, not like a code-repo `mage/`. (Identical to
 * {@link hubProjectPath}; kept as a distinct name for call-site intent.)
 */
export function hubProjectDocsRoot(
  hubRoot: string,
  projectName: string,
): string {
  return hubProjectPath(hubRoot, projectName);
}

/**
 * The single transient-state home for a resolved docs root (ADR-0025) —
 * `<docsRoot>/.mage`. Git-ignored, per-KB. Parent of the learnings/metrics/staging
 * leaves; the {@link learningsPath}/{@link metricsPath}/{@link stagingPath} helpers
 * resolve those — prefer them over re-joining STATE_DIR at the call site.
 */
export function stateDir(docsRoot: string): string {
  return join(docsRoot, STATE_DIR);
}

/**
 * The pre-promotion scratch dir for a resolved docs root —
 * `<docsRoot>/.mage/learnings`. Git-ignored, per-KB. Holds the raw, auto-pruned
 * per-session capture `*.jsonl` streams (ADR-0018) that distill folds.
 */
export function learningsPath(docsRoot: string): string {
  return join(stateDir(docsRoot), LEARNINGS_DIR);
}

/**
 * The metrics dir for a resolved docs root — `<docsRoot>/.mage/metrics`.
 * Git-ignored, per-KB. Holds the rollups, distill/promote watermarks, and the
 * accept/reject ledgers (ADR-0021).
 */
export function metricsPath(docsRoot: string): string {
  return join(stateDir(docsRoot), METRICS_DIR);
}

/**
 * The grooming-loop staging dir for a resolved docs root (0.0.12) —
 * `<docsRoot>/.mage/staging`. Git-ignored, per-KB (in a hub, each project gets its
 * own, since the docs root IS the project dir). Holds `<slug>.md` lesson drafts
 * that `mage stage` writes and `mage groom` promotes.
 */
export function stagingPath(docsRoot: string): string {
  return join(stateDir(docsRoot), STAGING_DIR);
}

// ─── reading ─────────────────────────────────────────────────────────────

/**
 * Read and parse a code repo's mage metadata file, if present. Returns null if
 * absent. Reads BOTH schema v1 and v2 leniently: a v1 file is normalized to the
 * v2 shape IN MEMORY (mode "in-repo" + non-empty hub_refs ⇒ "hybrid"), but the
 * returned object's `schema` field is the ON-DISK value — so `status`/`doctor`
 * can still report a v1 file as needing `mage migrate`. Only a genuinely foreign
 * schema throws. On the capture hot path: kept cheap and total.
 */
export async function readMetadata(
  codeRepo: string,
): Promise<MageMetadata | null> {
  const path = metadataPath(codeRepo);
  let raw: string;
  try {
    raw = await readFile(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(raw) as Record<string, unknown>;
  } catch {
    throw new Error(
      `metadata.json at ${path} is not valid JSON (possible merge conflict or partial write). ` +
        `Delete it and run \`mage init\` or \`mage link\` to recreate.`,
    );
  }
  const schema = String(parsed.schema ?? "");
  if (schema !== METADATA_SCHEMA && schema !== METADATA_SCHEMA_V1) {
    throw new Error(
      `Unknown mage metadata schema at ${path}: ${schema || "(missing)"}. ` +
        `Expected ${METADATA_SCHEMA}. Run \`mage migrate\` to upgrade, or delete and run \`mage init\`/\`mage link\` to recreate.`,
    );
  }
  return normalizeMetadata(parsed as unknown as MageMetadata);
}

/**
 * v1 → v2 in-memory normalization for code-repo metadata: makes hybrid explicit
 * (mode "in-repo" + non-empty hub_refs ⇒ "hybrid"). Idempotent on a v2 object,
 * and immutable — returns the same object when nothing changed (cheap hot path),
 * a new object otherwise. Leaves `schema` untouched; {@link writeMetadata} stamps
 * the current schema on write.
 */
export function normalizeMetadata(meta: MageMetadata): MageMetadata {
  const mode =
    (meta.mode as string) === "in-repo" && (meta.hub_refs?.length ?? 0) > 0
      ? "hybrid"
      : meta.mode;
  return mode === meta.mode ? meta : { ...meta, mode };
}

/**
 * Read and parse a hub's top-level metadata.json. Returns null if absent. Reads
 * schema v1 and v2 leniently and normalizes v1 in memory (HubProject.storage
 * "in-repo" ⇒ "repo-owned"); the returned `schema` is the on-disk value. Only a
 * genuinely foreign schema throws.
 */
export async function readHubMetadata(
  hubRoot: string,
): Promise<HubMetadata | null> {
  const path = hubMetadataPath(hubRoot);
  let raw: string;
  try {
    raw = await readFile(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(raw) as Record<string, unknown>;
  } catch {
    throw new Error(
      `Hub metadata.json at ${path} is not valid JSON (possible merge conflict or partial write). ` +
        `Delete it and run \`mage link\` to recreate.`,
    );
  }
  const schema = String(parsed.schema ?? "");
  if (schema !== METADATA_SCHEMA && schema !== METADATA_SCHEMA_V1) {
    throw new Error(
      `Unknown mage hub metadata schema at ${path}: ${schema || "(missing)"}. ` +
        `Expected ${METADATA_SCHEMA}. Run \`mage migrate\` to upgrade, or delete and re-run \`mage link\`.`,
    );
  }
  return normalizeHubMetadata(parsed as unknown as HubMetadata);
}

/**
 * v1 → v2 in-memory normalization for hub metadata: renames each project's
 * storage "in-repo" ⇒ "repo-owned". Idempotent and immutable (same object when
 * nothing changed). Leaves `schema` untouched; {@link writeHubMetadata} stamps it.
 */
export function normalizeHubMetadata(hub: HubMetadata): HubMetadata {
  if (!Array.isArray(hub.projects)) return hub;
  let changed = false;
  const projects = hub.projects.map((p) => {
    if ((p.storage as string) === "in-repo") {
      changed = true;
      return { ...p, storage: "repo-owned" as const };
    }
    return p;
  });
  return changed ? { ...hub, projects } : hub;
}

// ─── writing ─────────────────────────────────────────────────────────────

/**
 * Write a code repo's metadata, ALWAYS stamping the current schema
 * ({@link METADATA_SCHEMA}). Routing every writer through this guarantees a
 * read-modify-write upgrades a v1 file to v2 (lazy migration) and that no spread
 * accidentally persists a stale schema. Trailing newline for clean git diffs.
 */
export async function writeMetadata(
  codeRepo: string,
  meta: MageMetadata,
): Promise<void> {
  const stamped: MageMetadata = { ...meta, schema: METADATA_SCHEMA };
  await writeFile(
    metadataPath(codeRepo),
    `${JSON.stringify(stamped, null, 2)}\n`,
  );
}

/** Write a hub's top-level metadata, always stamping {@link METADATA_SCHEMA}. */
export async function writeHubMetadata(
  hubRoot: string,
  hub: HubMetadata,
): Promise<void> {
  const stamped: HubMetadata = { ...hub, schema: METADATA_SCHEMA };
  await writeFile(
    hubMetadataPath(hubRoot),
    `${JSON.stringify(stamped, null, 2)}\n`,
  );
}

// ─── structural checks ──────────────────────────────────────────────────

/** What {@link resolveDocsRoot} resolves to: the docs root to operate on, its
 *  kind, and the git repo the sinks live under (== root for a repo-KB/hub; the hub
 *  for an external project, whose docs live inside the hub's repo). `kind` is the
 *  2-value umbrella — "repo" covers BOTH in-repo and hybrid (both store locally);
 *  callers that must distinguish re-read `meta.mode`. */
export interface ResolvedDocsRoot {
  root: string;
  kind: "repo" | "hub";
  repo: string;
}

/**
 * The nearest ancestor of `startDir` (inclusive) carrying `mage/metadata.json` — the
 * CODE REPO root, which for mode=external is NOT the docs root (that lives in the hub).
 * Callers needing the metadata itself pair this with {@link readMetadata}. Returns null
 * when no code-repo KB is found walking up to the filesystem root.
 */
export async function findCodeRepoRoot(startDir: string): Promise<string | null> {
  let dir = absolutePath(startDir);
  for (;;) {
    if (await exists(join(dir, META_DIR, META_FILE))) return dir;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

export type HubUnreachableReason =
  | "malformed-config"
  | "no-hub-target"
  | "hub-absent"
  | "hub-corrupted"
  | "unknown-failure";

export type ExternalDocsRootResult =
  | { kind: "resolved"; value: ResolvedDocsRoot }
  | { kind: "not-external" }
  | {
      kind: "hub-unreachable";
      reason: HubUnreachableReason;
      expected?: string;
    };

/**
 * Resolve the mage docs root to operate on, starting from `startDir` (default cwd):
 *  - repo KB:  the nearest ancestor with `mage/metadata.json` (mode=in-repo or
 *              mode=hybrid) → that repo's `mage/`. Reported as kind "repo".
 *  - external: that metadata is mode=external → the HUB project it points to
 *              (`<hub_path>/projects/<project>/`), so captures/grooming land in the
 *              hub, not the code repo. Reported as kind "hub" (a hub-owned project
 *              is a flat docs root living inside the hub's repo); `repo` is the hub.
 *  - hub:      `startDir` is a hub root, or sits inside one. Inside a hub-owned
 *              project dir (`<hub>/projects/<name>/…`) → that project's flat docs
 *              root; the hub root or elsewhere under it → the hub root. Kind "hub".
 * Returns null if none is found, or if external mode hub is unreachable (never degrades
 * an unreachable external hub to repo KB). Never throws — this is on the capture hot path.
 */
export async function resolveDocsRoot(
  startDir: string,
): Promise<ResolvedDocsRoot | null> {
  const abs = absolutePath(startDir);

  // Walk up looking for a code-repo `mage/metadata.json` (in-repo/hybrid/external).
  const codeRepo = await findCodeRepoRoot(abs);
  if (codeRepo) {
    // Honor mode=external by following hub_path/hub_repo.
    // If external metadata exists but hub is unreachable, return null (do NOT fall back to repo KB).
    const external = await externalDocsRoot(codeRepo);
    if (external.kind === "resolved") return external.value;
    if (external.kind === "hub-unreachable") return null;
    return { root: codeRepoDocsRoot(codeRepo), kind: "repo", repo: codeRepo };
  }

  // Otherwise, walk up looking for a hub root. `startDir` may BE the hub, or sit
  // INSIDE it — most importantly inside a hub-owned project dir
  // (`<hub>/projects/<name>/`), a flat docs root the hub owns but which carries no
  // metadata.json of its own. Resolving it is what lets `mage <engine> --dir
  // <hub>/projects/<name>/` (the Decision 1 groom fan-out) reach the project's
  // own `.learnings/` even when its member code repo is absent on this machine.
  let dir = abs;
  for (;;) {
    if (await looksLikeHub(dir)) return hubDocsRoot(dir, abs);
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  return null;
}

/**
 * Resolve the docs root to operate on, or THROW the canonical "no knowledge base" error. The
 * resolve-or-throw every interactive command opens with: `dir` defaults to cwd and walks up
 * ({@link resolveDocsRoot}). The hook path (the boundary nudge) must NOT use this — it pairs
 * resolveDocsRoot with a fail-open `.catch(() => null)` so a missing KB never breaks session start.
 */
export async function requireDocsRoot(dir?: string): Promise<ResolvedDocsRoot> {
  const start = absolutePath(dir ?? process.cwd());
  const resolved = await resolveDocsRoot(start);
  if (!resolved) {
    throw new Error(
      `No mage knowledge base found at or above ${start}. Run \`mage init\` or \`mage link\` first.`,
    );
  }
  return resolved;
}

/**
 * Resolve a docs root given that `hub` is a hub root and `abs` is at or below it.
 * Inside `<hub>/projects/<name>/…` → that project's flat docs root; the hub root
 * itself or anywhere else under it → the hub root. Always kind "hub" (the hub repo
 * owns the files).
 */
function hubDocsRoot(hub: string, abs: string): ResolvedDocsRoot {
  const rel = relative(hub, abs);
  if (rel && !rel.startsWith("..") && !isAbsolute(rel)) {
    const [top, name] = rel.split(sep);
    if (top === PROJECTS_DIR && name) {
      return { root: hubProjectDocsRoot(hub, name), kind: "hub", repo: hub };
    }
  }
  return { root: hub, kind: "hub", repo: hub };
}

/**
 * If the code repo at `dir` is linked in external mode, returns the resolved hub project
 * docs root or a hub-unreachable result explaining why it cannot be resolved; otherwise
 * returns not-external (caller falls back to repo-KB handling).
 * ADR-0043 resolution order, via the ONE shared {@link chosenHubRoot}:
 *
 *   1. `hub_repo` present → derive its path, and use it only if BOTH arrival
 *      checks pass ({@link verifyHubArrival}: hub-shaped + origin matches).
 *   2. Else (absent, wrong shape, unreadable origin, OR a hard origin
 *      MISMATCH) fall back to `hub_path`, gated on the same shape check —
 *      the deprecated transition path (ADR-0043 §6).
 *   3. Else hub-unreachable — returns `{ kind: "hub-unreachable", reason, expected }`;
 *      {@link resolveDocsRoot} returns null (does NOT degrade to repo KB).
 *      This function must never throw for any case (the hot-path contract).
 */
export async function externalDocsRoot(dir: string): Promise<ExternalDocsRootResult> {
  try {
    const meta = await readMetadata(dir);
    if (!meta || meta.mode !== "external") return { kind: "not-external" };

    const expected = meta.hub_repo ?? meta.hub_path ?? undefined;
    if (!meta.project) {
      return { kind: "hub-unreachable", reason: "malformed-config", expected };
    }

    const chosen = chosenHubRoot(meta.hub_repo, meta.hub_path);
    if (!chosen) {
      return { kind: "hub-unreachable", reason: "no-hub-target", expected };
    }

    let hubRoot: string;
    if (chosen.source === "derived") {
      const arrival = await verifyHubArrival(chosen.root, meta.hub_repo as string);
      if (arrival.ok) {
        hubRoot = chosen.root;
      } else if (meta.hub_path && (await looksLikeHub(meta.hub_path))) {
        hubRoot = meta.hub_path; // fall back to the deprecated hub_path (incl. on a mismatch)
      } else {
        return { kind: "hub-unreachable", reason: "hub-absent", expected: chosen.root };
      }
    } else {
      if (!(await looksLikeHub(chosen.root))) {
        return { kind: "hub-unreachable", reason: "hub-corrupted", expected: chosen.root };
      }
      hubRoot = chosen.root;
    }

    return {
      kind: "resolved",
      value: {
        root: hubProjectDocsRoot(hubRoot, meta.project),
        kind: "hub",
        repo: hubRoot,
      },
    };
  } catch {
    return { kind: "hub-unreachable", reason: "unknown-failure" };
  }
}

/**
 * Every docs root a resolved KB OWNS — the canonical hub fan-out set (Decision 1 /
 * ADR-0011). For a repo KB, or a hub-owned PROJECT (root ≠ repo), just `[root]`. At a
 * hub ROOT (kind "hub", root === repo): the hub's own docs root PLUS every registered
 * `projects/<name>/`. This is the ONE enumerator the groom fan-out grooms, doctor's
 * layout-drift probe checks, and `mage migrate` relocates — sharing it is what keeps
 * those three from drifting apart. Fail-open: unreadable/absent hub metadata yields
 * just `[root]`; a registered project whose name is path-hostile (rejected by
 * {@link assertSafeName}) is skipped, never thrown.
 */
export async function ownedDocsRoots(kb: ResolvedDocsRoot): Promise<string[]> {
  const roots = [kb.root];
  if (kb.kind === "hub" && kb.root === kb.repo) {
    const meta = await readHubMetadata(kb.repo).catch(() => null);
    for (const p of meta?.projects ?? []) {
      if (!p.name) continue;
      try {
        roots.push(hubProjectDocsRoot(kb.repo, p.name));
      } catch {
        // assertSafeName rejected a hostile project name — skip it, never throw.
      }
    }
  }
  return roots;
}

/**
 * One (hub_repo, hub_path) pair's resolution, as picked by the single shared
 * {@link chosenHubRoot} — plus the `hubRepo` that produced a "derived" root, so
 * a caller that needs to scan for a displaced clone or offer clone-on-demand
 * has the canonical address without re-deriving it.
 */
export interface HubTarget {
  root: string;
  source: ChosenHubRootSource;
  /** Present only when `source === "derived"` — the hub_repo that derived `root`. */
  hubRepo?: string;
  /**
   * The pair's `hub_path`, when the metadata carries one — regardless of
   * `source`. A caller doing the full ADR-0043 §3 arrival check (shape +
   * origin match) on a "derived" root falls back to THIS when arrival fails
   * for a reason short of a hard mismatch (absent / wrong shape / unreadable
   * origin) — the same fallback {@link resolveDocsRoot}'s `externalDocsRoot`
   * performs, so a grant decision never drifts from a docs-root decision.
   */
  hubPath?: string;
}

/**
 * The out-of-repo KB roots a code repo's metadata resolves to — what a harness
 * must be granted access to before the agent can read its own knowledge base
 * (ADR-0042, the reach tier), now sourced via ADR-0043 derivation. EVERY call
 * site that needs to answer "which hub root does this pair resolve to" routes
 * through {@link chosenHubRoot} via this function — the previous attempt had
 * two independently written lookups drift (one gated on `existsSync`, one
 * didn't), silently skipping a permission grant whenever the hub wasn't yet
 * cloned. `chosenHubRoot` is pure and synchronous (no filesystem access), so
 * that particular drift is structurally impossible now.
 *
 *   - in-repo  → `[]`  (docs sit at `<repo>/mage/`, already under the project root)
 *   - external → the ONE hub pair's chosen root (hub_repo-derived, falling back
 *                to hub_path) — the hub REPO root, not the project docs root
 *                beneath it.
 *   - hybrid   → every `hub_refs[]` pair's chosen root.
 *
 * Harness-NEUTRAL by design (ADR-0036): this returns paths, never policy.
 * Paths at or under `projectRoot` are dropped (self-referential when cwd is
 * inside the hub itself). Order-stable, de-duplicated, and pure — no
 * filesystem access, so an absent/unverified hub is the CALLER's business to
 * detect (connect skips it, offering a scan/clone; doctor reports it).
 */
export function outOfRepoKbTargets(meta: MageMetadata, projectRoot: string): HubTarget[] {
  const normalized = normalizeMetadata(meta);
  const pairs: { hubRepo: string | null; hubPath: string | null }[] =
    normalized.mode === "external"
      ? [{ hubRepo: normalized.hub_repo, hubPath: normalized.hub_path }]
      : normalized.mode === "hybrid"
        ? normalized.hub_refs.map((r) => ({ hubRepo: r.hub_repo, hubPath: r.hub_path }))
        : [];

  const seen = new Set<string>();
  const out: HubTarget[] = [];
  for (const { hubRepo, hubPath } of pairs) {
    const chosen = chosenHubRoot(hubRepo, hubPath);
    if (!chosen) continue;
    const abs = absolutePath(chosen.root);
    if (seen.has(abs)) continue;
    seen.add(abs);
    // Self-referential: cwd is inside the hub, so the hub is already reachable.
    if (isUnder(projectRoot, abs)) continue;
    out.push({
      root: abs,
      source: chosen.source,
      hubRepo: chosen.source === "derived" ? (hubRepo ?? undefined) : undefined,
      hubPath: hubPath ?? undefined,
    });
  }
  return out;
}

/** {@link outOfRepoKbTargets}, flattened to just the resolved paths — the shape
 *  most callers (doctor's grant check, `connect`'s base grant list) actually want. */
export function outOfRepoKbRoots(meta: MageMetadata, projectRoot: string): string[] {
  return outOfRepoKbTargets(meta, projectRoot).map((t) => t.root);
}

/** What {@link resolveHubGrant} decides for ONE {@link HubTarget}. */
export interface HubGrantResolution {
  /** The path to actually grant, or null when nothing is currently grantable. */
  root: string | null;
  reason: "derived" | "hub_path" | "mismatch" | "absent";
  /** Redacted diagnostic detail — present for "mismatch". */
  detail?: string;
}

/**
 * The SAME resolution `connect` uses to decide what to grant and doctor uses to
 * decide what to check for — the one place the full ADR-0043 §5 order (derive →
 * verify arrival → fall back to hub_path → hub-absent) is implemented, so the
 * two can never drift (the exact failure this spec calls out: two independently
 * written gates — one checking `existsSync`, one not — silently skipping a
 * permission grant).
 *
 *   - source "hub_path" → grantable iff hub-shaped ({@link looksLikeHub}; it's
 *     untrusted git-tracked input with no remote to origin-match).
 *   - source "derived" → the full ADR-0043 §3 arrival check
 *     ({@link verifyHubArrival}: shape + origin match).
 *       - ok → "derived", grant the derived root.
 *       - origin MISMATCH → "mismatch", root null — a hard, named failure that
 *         never silently falls back (never reused, never clobbered).
 *       - absent / wrong shape / unreadable origin → fall back to `hub_path`
 *         when the pair carries one and it's hub-shaped (mirrors
 *         `externalDocsRoot`'s fallback, so a grant decision never drifts from
 *         a docs-root decision); else "absent", root null.
 */
export async function resolveHubGrant(target: HubTarget): Promise<HubGrantResolution> {
  if (target.source === "hub_path") {
    return (await looksLikeHub(target.root))
      ? { root: target.root, reason: "hub_path" }
      : { root: null, reason: "absent" };
  }

  const arrival = await verifyHubArrival(target.root, target.hubRepo as string);
  if (arrival.ok) return { root: target.root, reason: "derived" };
  if (arrival.reason === "origin-mismatch") {
    return { root: null, reason: "mismatch", detail: arrival.detail };
  }
  if (target.hubPath && (await looksLikeHub(target.hubPath))) {
    return { root: target.hubPath, reason: "hub_path" };
  }
  return { root: null, reason: "absent" };
}

/** Resolve a path (relative → absolute relative to cwd). */
export function absolutePath(p: string): string {
  return isAbsolute(p) ? p : resolve(process.cwd(), p);
}

/** Read genre overrides from metadata.json (ADR-0041 §3). */
export async function readGenreOverrides(
  resolved: ResolvedDocsRoot,
  logWarn = false,
): Promise<Record<string, Genre>> {
  try {
    const meta =
      resolved.kind === "hub"
        ? await readHubMetadata(resolved.repo)
        : await readMetadata(resolved.repo);
    return resolveGenreOverrides(meta?.genres, logWarn);
  } catch {
    return {};
  }
}
