// Shared skill-generation constants + helpers. Used by `mage skills` (wing-skill
// generation), the dream applier's graduate/demote (Procedure skills), and
// skill-match's mage-skill recognition. Extracted so the GENERATED marker + target
// dirs + name prefixes have ONE source of truth (the applier must recognize exactly
// what the generator produced — same marker = "mage-owned, safe to mutate/remove").

/**
 * The marker that brands a SKILL.md as mage-GENERATED (vs hand-authored/bespoke).
 * The ONLY thing that authorizes the applier (and cleanGeneratedWingSkills) to
 * mutate/archive a skill — a file lacking it is bespoke and untouchable (ADR-0016 §3).
 * Text is historical ("mage skills"); semantically it means "mage-owned, not bespoke".
 */
export const GEN_MARKER = "<!-- GENERATED by `mage skills` — do not edit by hand. -->";

/** Broadest portable coverage: project-local skill dirs read by Claude + the agent-skills CLI. */
export const TARGET_AGENT_DIRS = [".claude/skills", ".agents/skills"];

/** Generated per-wing awareness skill prefix. */
export const WING_PREFIX = "mage-wing-";

/** Graduated Procedure-skill prefix (ADR-0013 §1 / CONVENTIONS §9). */
export const SKILL_PREFIX = "mage-skill-";

/**
 * Slugify a note title into a safe Procedure-skill slug — lower-case, non-alnum runs
 * → "-", trimmed, capped. Guaranteed to pass `safeSegment` (no "/", "\", "..", NUL,
 * never empty) so it can never drive a path traversal when used as a dir name.
 */
export function procedureSkillSlug(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48)
    .replace(/-+$/g, "");
  return slug.length > 0 ? slug : "note";
}

/** The full Procedure-skill name for a slug: `mage-skill-<slug>`. */
export function procedureSkillName(slug: string): string {
  return `${SKILL_PREFIX}${slug}`;
}

/**
 * Render a free-form string as a SAFE YAML scalar value for a `description:` line.
 * A simple inline scalar (alnum-led, no newline/colon/`#`, and not surrounded by
 * whitespace) is returned verbatim — plain and readable. Anything else (newlines,
 * colons, leading/trailing space) is `JSON.stringify`'d into a valid YAML double-
 * quoted scalar, which escapes the newlines so js-yaml parses it as ONE string
 * value. This prevents a crafted description from injecting extra frontmatter keys
 * (e.g. a second `name:`/`wing:`) — the whole payload stays a single value.
 */
export function yamlDescriptionValue(s: string): string {
  if (/^[A-Za-z0-9][^\n\r:#]*$/.test(s) && s.trim() === s) return s;
  return JSON.stringify(s);
}
